force-app/main/default/objects/Account/fields/Average_Margin__c.field-meta.xml
<CustomField>
    <fullName>Average_Margin__c</fullName>
    <label>Average Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/BSLS_ID__c.field-meta.xml
<CustomField>
    <fullName>BSLS_ID__c</fullName>
    <label>BSLS ID</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>ORD-{MM}/{YY}-{000}</displayFormat>
        <label>Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account_Order__c.field-meta.xml
<CustomField>
    <fullName>Account_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/BSLS_ID__c.field-meta.xml
<CustomField>
    <fullName>BSLS_ID__c</fullName>
    <externalId>true</externalId>
    <label>BSLS ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Confirmed</fullName>
                <default>true</default>
                <label>Confirmed</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>CRO Amendment Awaited</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>Order Item-{0000}</displayFormat>
        <label>Order Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/BSLS_ID__c.field-meta.xml
<CustomField>
    <fullName>BSLS_ID__c</fullName>
    <label>BSLS ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Customer_Port_Pair_Margin__c.field-meta.xml
<CustomField>
    <fullName>Customer_Port_Pair_Margin__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Port Pair Margin</label>
    <referenceTo>Route_Profit_Margin__c</referenceTo>
    <relationshipLabel>Order Items (Customer Port Pair Margin)</relationshipLabel>
    <relationshipName>Order_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Port_of_Discharge_Order__c.field-meta.xml
<CustomField>
    <fullName>Port_of_Discharge_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Port of Discharge</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Port_of_Loading_Order__c.field-meta.xml
<CustomField>
    <fullName>Port_of_Loading_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Port of Loading</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipLabel>Order Items1</relationshipLabel>
    <relationshipName>Order_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Profit__c.field-meta.xml
<CustomField>
    <fullName>Profit__c</fullName>
    <formula>(Total_Order__c - Buying_Rate__c) *  Teus__c</formula>
    <label>Profit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Profit_Margin__c.field-meta.xml
<CustomField>
    <fullName>Profit_Margin__c</fullName>
    <formula>( Total_Order__c -  Buying_Rate__c ) / Buying_Rate__c</formula>
    <label>Profit Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Route_Profit_Margin__c.field-meta.xml
<CustomField>
    <fullName>Route_Profit_Margin__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route Pair Margin</label>
    <referenceTo>Route_Profit_Margin__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Teus__c.field-meta.xml
<CustomField>
    <fullName>Teus__c</fullName>
    <formula>Quantity__c *  Equipment_Type_Order__r.Teus__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Teus</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Port__c/Port__c.object-meta.xml
<CustomObject>
    <label>Port</label>
    <nameField>
        <label>Port Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Port__c/fields/BSLS_ID__c.field-meta.xml
<CustomField>
    <fullName>BSLS_ID__c</fullName>
    <label>BSLS ID</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Route_Profit_Margin__c/Route_Profit_Margin__c.object-meta.xml
<CustomObject>
    <label>Route Profit Margin</label>
    <nameField>
        <label>Route Profit Margin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Profit Margins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Route_Profit_Margin__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Route Profit Margins</relationshipLabel>
    <relationshipName>Route_Profit_Margins</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route_Profit_Margin__c/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <label>Margin</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Route_Profit_Margin__c/fields/Order_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Item</label>
    <referenceTo>Order_Item__c</referenceTo>
    <relationshipLabel>Route Profit Margins</relationshipLabel>
    <relationshipName>Route_Profit_Margins</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route_Profit_Margin__c/fields/Port_of_Discharge__c.field-meta.xml
<CustomField>
    <fullName>Port_of_Discharge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Port of Discharge</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipLabel>Route Profit Margins (Port of Discharge)</relationshipLabel>
    <relationshipName>Route_Profit_Margins_POD</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route_Profit_Margin__c/fields/Port_of_Loading__c.field-meta.xml
<CustomField>
    <fullName>Port_of_Loading__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Port of Loading</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipLabel>Route Profit Margins</relationshipLabel>
    <relationshipName>Route_Profit_Margins_POL</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route_Profit_Margin__c/recordTypes/Customer_Port_Pair.recordType-meta.xml
<RecordType>
    <fullName>Customer_Port_Pair</fullName>
    <active>true</active>
    <label>Customer Port Pair</label>
</RecordType>

force-app/main/default/objects/Route_Profit_Margin__c/recordTypes/Port_Pair.recordType-meta.xml
<RecordType>
    <fullName>Port_Pair</fullName>
    <active>true</active>
    <label>Port Pair</label>
</RecordType>

force-app/main/default/classes/BAFCOMarginCalculator.cls
public class BAFCOMarginCalculator { 
    public static void calculateMargins(List<Order_Item__c> orderItemList){
        system.debug('=orderItemList '+orderItemList.size());
        for(Order_Item__c ordItem:orderItemList){
            calculateCustomerMargin(ordItem);
            calculateRouteMargin(ordItem);
            calculateRouteCustomerMargin(ordItem);
        }
    }    
    
    public static void calculateCustomerMargin(Order_Item__c ordItemValue){
        Decimal profitTeusSum=0;
        Decimal TeusSum=0;
        Set<ID> orderIDSet = new Set<ID>();
        Set<ID> customerIDSet = new Set<ID>();
        Map<ID,ID> customerItemMap = new Map<ID,ID>();
        Map<ID,Decimal> customerMarginMap = new Map<ID,Decimal>();
        
        String customerID = [SELECT id,Account_Order__r.id FROM Order__c WHERE id =:ordItemValue.Order__c Limit 1].Account_Order__r.id;
        
        Account customerRec = [Select id,Average_Margin__c from Account Where Id=:customerID];
        
        List<Order_Item__c> toProcessItemList = [Select ID,Order__r.Account_Order__c,Profit__c,
                                                 Order__r.Account_Order__r.Average_Margin__c,BSLS_ID__c,Teus__c,
                                                 Profit_Margin__c,Quantity__c
                                                 FROM Order_Item__c 
                                                 WHERE Order__r.Account_Order__c =:customerID
                                                 AND Order__r.Status__c='Confirmed'];
        
        system.debug('toProcessItemList'+toProcessItemList);
        system.debug('toProcessItemList Size'+toProcessItemList.size());
        Decimal finalMarginValue;
        for(Order_Item__c ordItem:toProcessItemList){            
            if(ordItem.Profit_Margin__c !=NULL && ordItem.Quantity__c!=NULL){
                profitTeusSum=profitTeusSum+(ordItem.Profit_Margin__c * ordItem.Quantity__c);
                TeusSum=TeusSum+ordItem.Quantity__c;
            }
        }
        
        system.debug('==profitTeusSum '+profitTeusSum);
        system.debug('==TeusSum '+TeusSum);
        if(profitTeusSum!=0 || TeusSum!=0){
            Decimal averageMargin = profitTeusSum/TeusSum;
            system.debug('=averageMargin '+averageMargin);
            if(customerRec.Average_Margin__c == NULL){
                finalMarginValue = 0 + averageMargin;
            }
            else{
                if(customerRec.Average_Margin__c!=finalMarginValue){
                    finalMarginValue = averageMargin;
                }
            }
            system.debug('=finalMarginValue'+finalMarginValue);
            customerRec.Average_Margin__c = (finalMarginValue).setScale(2);
            
            if(customerRec!=NULL){
                database.update(customerRec);
            }
        }    
    }
    
    public static void calculateRouteMargin(Order_Item__c ordItemValue){
        RecordType RouteMarginRecordType = [SELECT Id, SobjectType, DeveloperName, Name FROM RecordType Where SobjectType='Route_Profit_Margin__c' And DeveloperName = 'Port_Pair' Limit 1];
        Decimal profitTeusSum=0;
        Decimal TeusSum=0;
        Order_Item__c orderItemDetails = [SELECT id,Order__r.Account_Order__r.Name,Order__r.Account_Order__r.id,
                                          Port_of_Loading_Order__r.Name,Port_of_Discharge_Order__r.Name,
                                          Profit_Margin__c,Quantity__c
                                          FROM Order_Item__c 
                                          WHERE id=:ordItemValue.ID];
                                          //AND Order__r.Status__c='Confirmed'];
        
        
        List<Route_Profit_Margin__c> routeMargingList = [Select id,Margin__c 
                                                         from Route_Profit_Margin__c 
                                                         Where Port_of_Loading__c=:ordItemValue.Port_of_Loading_Order__c 
                                                         AND Port_of_Discharge__c=:ordItemValue.Port_of_Discharge_Order__c Limit 1];
        Route_Profit_Margin__c routeRecordToUpdate;
        
        if(routeMargingList==NULL || routeMargingList.size()<1){
            Route_Profit_Margin__c newRouteRecord = new Route_Profit_Margin__c();
            newRouteRecord.Margin__c=0;
            newRouteRecord.Port_of_Loading__c=ordItemValue.Port_of_Loading_Order__c;
            newRouteRecord.Port_of_Discharge__c=ordItemValue.Port_of_Discharge_Order__c;
            //newRouteRecord.Order_Item__c=ordItemValue.Id;
            //newRouteRecord.Customer__c = orderItemDetails.Order__r.Account_Order__r.ID;
            //newRouteRecord.Name=orderItemDetails.Order__r.Account_Order__r.Name+' || '+orderItemDetails.Port_of_Loading_Order__r.Name+' || '+orderItemDetails.Port_of_Discharge_Order__r.Name;
            newRouteRecord.Name=orderItemDetails.Port_of_Loading_Order__r.Name+' || '+orderItemDetails.Port_of_Discharge_Order__r.Name;
            newRouteRecord.RecordTypeId=RouteMarginRecordType.Id;
            database.insert(newRouteRecord);
            routeRecordToUpdate=newRouteRecord;
        }
        else{
            routeRecordToUpdate=routeMargingList[0];
        }
        if(ordItemValue.Route_Profit_Margin__c==NULL && !System.isFuture() && !System.isBatch()){
            updateRouteOnItem(ordItemValue.id,routeRecordToUpdate.Id,False);  
        }
        
        
        List<Order_Item__c> toProcessItemList = [Select ID,Port_of_Discharge_Order__c,Port_of_Loading_Order__c,Profit__c,Profit_Margin__c, Teus__c, Quantity__c
                                                 FROM Order_Item__c 
                                                 WHERE Port_of_Loading_Order__c=:ordItemValue.Port_of_Loading_Order__c 
                                                 AND Port_of_Discharge_Order__c=:ordItemValue.Port_of_Discharge_Order__c
                                                 AND Order__r.Status__c='Confirmed'];
        
        system.debug('toProcessItemList'+toProcessItemList);
        system.debug('toProcessItemList Size'+toProcessItemList.size());
        Decimal finalMarginValue;
        
        for(Order_Item__c ordItem:toProcessItemList){            
            if(ordItem.Profit_Margin__c !=NULL && ordItem.Quantity__c!=NULL){
                profitTeusSum=profitTeusSum+(ordItem.Profit_Margin__c *ordItem.Quantity__c);
                TeusSum=TeusSum+ordItem.Quantity__c;
            }
        }
        
        system.debug('==profitTeusSum '+profitTeusSum);
        system.debug('==TeusSum '+TeusSum);
        if(profitTeusSum!=0 || TeusSum!=0){
            Decimal averageMargin = profitTeusSum/TeusSum;
            system.debug('=averageMargin '+averageMargin);
            if(routeRecordToUpdate.Margin__c == NULL){
                finalMarginValue = 0 + averageMargin;
            }
            else{
                if(routeRecordToUpdate.Margin__c!=finalMarginValue){
                    finalMarginValue = (averageMargin).setScale(2);
                }
            }
            system.debug('=finalMarginValue'+finalMarginValue);
            routeRecordToUpdate.Margin__c = finalMarginValue;
            
            if(routeRecordToUpdate!=NULL){
                database.update(routeRecordToUpdate);
            }
        }    
    }
    
    public static void calculateRouteCustomerMargin(Order_Item__c ordItemValue){
        RecordType RouteCustomerMarginRecordType = [SELECT Id, SobjectType, DeveloperName, Name FROM RecordType Where SobjectType='Route_Profit_Margin__c' And DeveloperName = 'Customer_Port_Pair' Limit 1];
        Decimal profitTeusSum=0;
        Decimal TeusSum=0;
        Order_Item__c orderItemDetails = [SELECT id,Order__r.Account_Order__r.Name,Order__r.Account_Order__r.id,Port_of_Loading_Order__r.Name,Port_of_Discharge_Order__r.Name,Profit_Margin__c,Quantity__c
                                          FROM Order_Item__c 
                                          WHERE id=:ordItemValue.ID];
        
        
        List<Route_Profit_Margin__c> routeMargingList = [Select ID,Margin__c 
                                                         from Route_Profit_Margin__c 
                                                         Where Port_of_Loading__c=:ordItemValue.Port_of_Loading_Order__c 
                                                         AND Port_of_Discharge__c=:ordItemValue.Port_of_Discharge_Order__c 
                                                         AND Customer__c=:orderItemDetails.Order__r.Account_Order__c Limit 1];
        Route_Profit_Margin__c routeRecordToUpdate;
        
        if(routeMargingList==NULL || routeMargingList.size()<1){
            Route_Profit_Margin__c newRouteRecord = new Route_Profit_Margin__c();
            newRouteRecord.Margin__c=0;
            newRouteRecord.Port_of_Loading__c=ordItemValue.Port_of_Loading_Order__c;
            newRouteRecord.Port_of_Discharge__c=ordItemValue.Port_of_Discharge_Order__c;
            newRouteRecord.Customer__c = orderItemDetails.Order__r.Account_Order__r.ID;
            newRouteRecord.Name=orderItemDetails.Order__r.Account_Order__r.Name+' || '+orderItemDetails.Port_of_Loading_Order__r.Name+' || '+orderItemDetails.Port_of_Discharge_Order__r.Name;
            newRouteRecord.RecordTypeId=RouteCustomerMarginRecordType.Id;
            database.insert(newRouteRecord);
            routeRecordToUpdate=newRouteRecord;
        }
        else{
            routeRecordToUpdate=routeMargingList[0];
        }
        if(ordItemValue.Customer_Port_Pair_Margin__c==NULL && !System.isFuture() && !System.isBatch()){
            updateRouteOnItem(ordItemValue.id,routeRecordToUpdate.Id,True);  
        }
        
        
        List<Order_Item__c> toProcessItemList = [Select ID,Port_of_Discharge_Order__c,Port_of_Loading_Order__c,Profit__c,Teus__c,Profit_Margin__c,Quantity__c
                                                 FROM Order_Item__c 
                                                 WHERE Port_of_Loading_Order__c=:ordItemValue.Port_of_Loading_Order__c 
                                                 AND Port_of_Discharge_Order__c=:ordItemValue.Port_of_Discharge_Order__c
                                                 AND Order__r.Account_Order__c=:orderItemDetails.Order__r.Account_Order__c
                                                 AND Order__r.Status__c='Confirmed'];
        
        system.debug('toProcessItemList'+toProcessItemList);
        system.debug('toProcessItemList Size'+toProcessItemList.size());
        Decimal finalMarginValue;
        
        for(Order_Item__c ordItem:toProcessItemList){            
            if(ordItem.Profit_Margin__c !=NULL && ordItem.Quantity__c!=NULL){
                profitTeusSum=profitTeusSum+(ordItem.Profit_Margin__c *ordItem.Quantity__c);
                TeusSum=TeusSum+ordItem.Quantity__c;
            }
        }
        
        system.debug('==profitTeusSum '+profitTeusSum);
        system.debug('==TeusSum '+TeusSum);
        if(profitTeusSum!=0 || TeusSum!=0){
            Decimal averageMargin = profitTeusSum/TeusSum;
            system.debug('=averageMargin '+averageMargin);
            if(routeRecordToUpdate.Margin__c == NULL){
                finalMarginValue = 0 + averageMargin;
            }
            else{
                if(routeRecordToUpdate.Margin__c!=finalMarginValue){
                    finalMarginValue = (averageMargin).setScale(2);
                }
            }
            system.debug('=finalMarginValue'+finalMarginValue);
            routeRecordToUpdate.Margin__c = finalMarginValue;
            
            if(routeRecordToUpdate!=NULL){
                database.update(routeRecordToUpdate);
            }
        }    
    }
    
    @future
    public static void updateRouteOnItem(ID orderItemID,ID routeMargingID,Boolean isCustomerRoutePair){
        system.debug('In updateRouteOnItem'+orderItemID);
        Order_Item__c updateItemValue= new Order_Item__c();
        if(isCustomerRoutePair){
            updateItemValue = new Order_Item__c(id=orderItemID,Customer_Port_Pair_Margin__c=routeMargingID);
        }
        else {
            updateItemValue = new Order_Item__c(id=orderItemID,Route_Profit_Margin__c=routeMargingID);
        }
        if(!test.isRunningTest()) database.update(updateItemValue);        
    } 
    
    public static void deleteOrderCharges(List<ID> orderIdSet){
        system.debug('orderIdSet'+orderIdSet);
        List<String> routeCustomerString = new List<String>();
        List<String> routePortPairString = new List<String>();
        List<Order_Item__c> orderItemList = [Select id,Port_of_Discharge_Order__r.Name,Port_of_Loading_Order__r.Name,
                                             Order__r.Account_Order__r.Name 
                                             from Order_Item__c
                                             where Order__c IN :orderIdSet];
        for(Order_Item__c ordItem:orderItemList){
            routeCustomerString.add(ordItem.Order__r.Account_Order__r.Name+' || '+ordItem.Port_of_Loading_Order__r.Name+' || '+ordItem.Port_of_Discharge_Order__r.Name);
            routePortPairString.add(ordItem.Port_of_Loading_Order__r.Name+' || '+ordItem.Port_of_Discharge_Order__r.Name);            
        }
        List<Route_Profit_Margin__c> routeMargingList = [Select ID,Margin__c 
                                                         from Route_Profit_Margin__c 
                                                         Where Name IN : routeCustomerString OR Name IN : routePortPairString];
        if(routeMargingList!=NULL){
            //database.delete(routeMargingList);
        }
        
        
    }
}