force-app/main/default/objects/Account/fields/Average_Credit_Days__c.field-meta.xml
<CustomField>
    <fullName>Average_Credit_Days__c</fullName>
    <label>Average Credit Days</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Average_Margin__c.field-meta.xml
<CustomField>
    <fullName>Average_Margin__c</fullName>
    <label>Average Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Best_Margin__c.field-meta.xml
<CustomField>
    <fullName>Best_Margin__c</fullName>
    <label>Best Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Branch</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <formula>TEXT(Owner.Branch__c)</formula>
    <label>Branch</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quotation__c/Quotation__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>JED-{MM}/{YY}-{000}</displayFormat>
        <label>Quotation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <formula>TEXT(Opportunity__r.Owner.Branch__c)</formula>
    <label>Branch</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <formula>TEXT(Enquiry__r.Business_Type__c)</formula>
    <label>Business Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <label>Customer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Effective_From__c.field-meta.xml
<CustomField>
    <fullName>Effective_From__c</fullName>
    <label>Effective From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Exclusions__c.field-meta.xml
<CustomField>
    <fullName>Exclusions__c</fullName>
    <label>Exclusions</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Inclusions__c.field-meta.xml
<CustomField>
    <fullName>Inclusions__c</fullName>
    <label>Inclusions</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quotation__c/recordTypes/Export.recordType-meta.xml
<RecordType>
    <fullName>Export</fullName>
    <active>true</active>
    <label>Export</label>
</RecordType>

force-app/main/default/globalValueSets/Branch.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Jeddah</fullName>
    </customValue>
    <customValue>
        <fullName>Riyadh</fullName>
    </customValue>
    <customValue>
        <fullName>Dammam</fullName>
    </customValue>
    <customValue>
        <fullName>Jubail</fullName>
    </customValue>
    <masterLabel>Branch</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Business_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Import</fullName>
    </customValue>
    <customValue>
        <fullName>Export</fullName>
    </customValue>
    <masterLabel>Business Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BAFCOGeneratePDFMobileControllerTest.cls
@isTest
public class BAFCOGeneratePDFMobileControllerTest {
    @TestSetup
    static void setup() {
        account acc = new Account();
        acc.Branch__c = 'Jeddah';
        acc.Average_Credit_Days__c = 2;
        acc.Average_Margin__c =2;
        acc.Best_Margin__c = 1;
        acc.name = 'test';
        insert acc;
        
        Contact con = new contact();
        con.FirstNAme = 'test';
        con.LastName = 'test';
        con.Email = 'test@email.com';
        con.MobilePhone = '0000000';
        con.AccountId = acc.id;
        insert con;
        
        opportunity opty = new Opportunity();
        opty.AccountId = acc.id;
        opty.StageName = 'Qualification';
        opty.CloseDate = system.today();
        opty.Name ='testopty';
        opty.Business_Type__c = 'Export';
        insert opty;
        
        Task tsk = new Task();
        tsk.Subject = 'Provide Quotation';
        tsk.Status = 'Open';
        tsk.OwnerId = UserInfo.getUserId();
        tsk.WhatId = opty.Id;
        tsk.IsReminderSet = true;
        tsk.ActivityDate = Date.valueOf(DateTime.now());
        insert tsk;
        
        integer year =  Date.Today().Year();
        string s1=string.valueof(year).right(2);
        Integer Year1= Integer.valueof(s1);
        
        Quotation__c quoteObj = new Quotation__c();
        quoteObj.Name__c= 'Quote/'+Year1+'/'+1;
        quoteObj.opportunity__c = opty.id;
        quoteObj.Customer_Name__c = 'test';
        quoteObj.Account__c = acc.id;
        quoteObj.Inclusions__c = 'Test Data ;;test data ;';
        quoteObj.Exclusions__c = 'Test Data ;;test data ;';
        quoteObj.Effective_From__c = system.today();
        Insert quoteObj;
        
    }
	 @isTest static void testController(){
        Quotation__c quoteObj = [Select id from Quotation__c limit 1];
        PageReference testPage = Page.BAFCOQuotePDFMobile; 
   		Test.setCurrentPage(testPage);
        testPage.getParameters().put('recordId', quoteObj.id);
        ApexPages.StandardController sc = new  ApexPages.StandardController(quoteObj); 
        BAFCOGeneratePDFMobileController ob = new BAFCOGeneratePDFMobileController(sc);
        ob.emailid = 'test@email.com';
        ob.send();
    }
}