force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Branch</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/BSLS_ID__c.field-meta.xml
<CustomField>
    <fullName>BSLS_ID__c</fullName>
    <label>BSLS ID</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Shipper.recordType-meta.xml
<RecordType>
    <fullName>Shipper</fullName>
    <active>true</active>
    <label>Shipper</label>
</RecordType>

force-app/main/default/objects/Consignee__c/Consignee__c.object-meta.xml
<CustomObject>
    <label>Consignee</label>
    <nameField>
        <displayFormat>Consignee-{00000}</displayFormat>
        <label>Consignee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consignees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Consignee__c/fields/Consignee__c.field-meta.xml
<CustomField>
    <fullName>Consignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consignee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Consignees</relationshipLabel>
    <relationshipName>Consignees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Consignee__c/fields/Order_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Item</label>
    <referenceTo>Order_Item__c</referenceTo>
    <relationshipLabel>Consignees</relationshipLabel>
    <relationshipName>Consignees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>ORD-{MM}/{YY}-{000}</displayFormat>
        <label>Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account_Order__c.field-meta.xml
<CustomField>
    <fullName>Account_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <formula>TEXT( Quotation__r.Opportunity__r.Owner.Branch__c )</formula>
    <label>Branch</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/BSLS_ID__c.field-meta.xml
<CustomField>
    <fullName>BSLS_ID__c</fullName>
    <externalId>true</externalId>
    <label>BSLS ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order__c/fields/Operations_Executive__c.field-meta.xml
<CustomField>
    <fullName>Operations_Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Operations Executive</label>
    <referenceTo>Operations_Executive__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Validity__c.field-meta.xml
<CustomField>
    <fullName>Order_Validity__c</fullName>
    <label>Order Validity</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Quotation__c.field-meta.xml
<CustomField>
    <fullName>Quotation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Quotation</label>
    <referenceTo>Quotation__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>Order Item-{0000}</displayFormat>
        <label>Order Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent</label>
    <referenceTo>Agent__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/BSLS_ID__c.field-meta.xml
<CustomField>
    <fullName>BSLS_ID__c</fullName>
    <label>BSLS ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Equipment_Type_Order__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Type_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment Type</label>
    <referenceTo>Equipment_Type__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Parent_OrderItem__c.field-meta.xml
<CustomField>
    <fullName>Parent_OrderItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>used for while cloning item so as to store related record thing.</description>
    <label>Parent OrderItem</label>
    <referenceTo>Order_Item__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Place_of_Pickup__c.field-meta.xml
<CustomField>
    <fullName>Place_of_Pickup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Place of Pickup</label>
    <referenceTo>Place__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Port_of_Discharge_Order__c.field-meta.xml
<CustomField>
    <fullName>Port_of_Discharge_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Port of Discharge</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Route_Order__c.field-meta.xml
<CustomField>
    <fullName>Route_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Shipping_Line__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Line</label>
    <referenceTo>Shipping_Line__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Port__c/Port__c.object-meta.xml
<CustomObject>
    <label>Port</label>
    <nameField>
        <label>Port Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Port__c/fields/BSLS_ID__c.field-meta.xml
<CustomField>
    <fullName>BSLS_ID__c</fullName>
    <label>BSLS ID</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Quotation__c/Quotation__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>JED-{MM}/{YY}-{000}</displayFormat>
        <label>Quotation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotation__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <formula>TEXT(Opportunity__r.Owner.Branch__c)</formula>
    <label>Branch</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Quotation_Validity__c.field-meta.xml
<CustomField>
    <fullName>Quotation_Validity__c</fullName>
    <label>Quotation Validity</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <displayFormat>ROT-{0000}</displayFormat>
        <label>Route Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/fields/Kind_Of_Shipment__c.field-meta.xml
<CustomField>
    <fullName>Kind_Of_Shipment__c</fullName>
    <label>Kind Of Shipment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LCL</fullName>
            </value>
            <value>
                <fullName>FCL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Route__c/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>P2P</fullName>
            </value>
            <value>
                <fullName>D2P</fullName>
            </value>
            <value>
                <fullName>P2D</fullName>
            </value>
            <value>
                <fullName>D2D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Route__c/fields/Shipping_Line__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Line</label>
    <referenceTo>Shipping_Line__c</referenceTo>
    <relationshipLabel>Routes</relationshipLabel>
    <relationshipName>Routes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipper__c/Shipper__c.object-meta.xml
<CustomObject>
    <label>Shipper</label>
    <nameField>
        <label>Shipper Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shippers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipper__c/fields/Order_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Item</label>
    <referenceTo>Order_Item__c</referenceTo>
    <relationshipLabel>Shippers</relationshipLabel>
    <relationshipName>Shippers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipper__c/fields/Shipper__c.field-meta.xml
<CustomField>
    <fullName>Shipper__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipper</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shippers</relationshipLabel>
    <relationshipName>Shippers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Line__c/Shipping_Line__c.object-meta.xml
<CustomObject>
    <label>Shipping Line</label>
    <nameField>
        <label>Shipping Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipping Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Line__c/fields/BSLS_ID__c.field-meta.xml
<CustomField>
    <fullName>BSLS_ID__c</fullName>
    <label>BSLS ID</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/Branch.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Jeddah</fullName>
    </customValue>
    <customValue>
        <fullName>Riyadh</fullName>
    </customValue>
    <customValue>
        <fullName>Dammam</fullName>
    </customValue>
    <customValue>
        <fullName>Jubail</fullName>
    </customValue>
    <masterLabel>Branch</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BAFCOSendOrdersAPI.cls
public class BAFCOSendOrdersAPI {
    public static OrderDetails getOrderData(List<Order__c> orderList) {
        String returnResult = '';
        List<OrderList> orderDtoList = new List<OrderList>();
        if(orderList.size() >0){
            Set<Id> orderItemIds = new Set<Id>();
            Map<Id,List<Consignee__c>> itemIdToConsigneeId = new Map<Id,List<Consignee__c>>();
            Map<Id,List<Shipper__c>> itemIdToShipperId = new Map<Id,List<Shipper__c>>();
            for(Order__c ordrObj : orderList){
                if(ordrObj.Order_Items__r.size() > 0){
                    for(Order_Item__c item : ordrObj.Order_Items__r){
                        orderItemIds.add(item.id);
                    }
                }
            }
            for(Consignee__c conObj : [Select id,Consignee__r.BSLS_ID__c,Order_Item__c,Consignee__r.Name,Consignee__r.Branch__c,Consignee__r.Owner.name,Consignee__r.BillingAddress from Consignee__c where Order_Item__c in : orderItemIds]){
                if(!itemIdToConsigneeId.containskey(conObj.Order_Item__c)){
                    itemIdToConsigneeId.put(conObj.Order_Item__c,new List<Consignee__c>());
                }
                itemIdToConsigneeId.get(conobj.Order_Item__c).add(conObj);
            }
            for(Shipper__c shipObj : [Select id,Shipper__r.BSLS_ID__c,Shipper__r.Name,Shipper__r.Branch__c,Order_Item__c,Shipper__r.Owner.name,Shipper__r.BillingAddress from Shipper__c where Order_Item__c in : orderItemIds ]){
                if(!itemIdToShipperId.containskey(shipObj.Order_Item__c)){
                    itemIdToShipperId.put(shipObj.Order_Item__c,new List<Shipper__c>());
                }
                itemIdToShipperId.get(shipObj.Order_Item__c).add(shipObj);
            }
            for(Order__c ordrObj : orderList){
                OrderList dto = new OrderList();
                if(ordrObj.Account_Order__c != null){
                    AccountObj accObj = new AccountObj();
                    accobj.AccountName = ordrObj.Account_Order__r.Name;
                    accobj.Branch = ordrObj.Account_Order__r.Branch__c;
                    accobj.AccountOwner = ordrObj.Account_Order__r.Owner.Name;
                    accobj.BillingAddress = String.valueOf(ordrObj.Account_Order__r.BillingAddress);
                    accobj.SFID = ordrObj.Account_Order__c;
                    accobj.BSLSID = ordrObj.Account_Order__r.BSLS_ID__c;
                    dto.AccountObj = accobj;
                }
                OrderObj orderDto = new OrderObj();
                orderDto.OrderNumber = ordrObj.Name;
                orderDto.QuotationNumber = ordrObj.Quotation__r.Name;
                orderDto.QuotationValidity = ordrObj.Quotation__r.Quotation_Validity__c;
                orderDto.OrderValidity = ordrObj.Order_Validity__c;
                if(ordrObj.Order_Items__r.size() > 0){
                    List<Order_Item__c> orderItemList = ordrObj.Order_Items__r;
                    List<OrderItemList> orderItemDtoList = new List<OrderItemList>();
                    for(Order_Item__c item : orderItemList){
                        OrderItemList itemDto = new OrderItemList();
                        itemDto.OrderNumber = item.Order__r.Name ;
                        itemDto.OrderItemNumber = item.Name ;
                        itemDto.opsExecutive = ordrObj.Operations_Executive__r.BSLS_ID__c ;
                        switch on item.Route_Order__r.Kind_Of_Shipment__c {
                            when 'FCL' {
                                itemDto.shipmentType = 1 ;
                            }
                            when else {
                                itemDto.shipmentType = 2 ;
                            }
                        }
                        switch on item.Route_Order__r.Service_Type__c {
                            when 'P2P' {
                                itemDto.serviceType = 1 ;
                            }
                            when 'P2D' {
                                itemDto.serviceType = 2 ;
                            }
                            when 'D2P' {
                                itemDto.serviceType = 3 ;
                            }
                            when else {
                                itemDto.serviceType = 4 ;
                            }
                        }
                        //itemDto.serviceType =  '';     //Not Mapped
                        //itemDto.shipmentType = '' ;    //Not Mapped
                        itemDto.shippingline = item.Shipping_Line__r.BSLS_ID__c ;
                        itemDto.portOfLoading = item.Port_of_Loading_Order__r.BSLS_ID__c ;
                        itemDto.portOfDestination = item.Port_of_Discharge_Order__r.BSLS_ID__c ;
                        itemDto.placeOfPickup = item.Place_of_Pickup__r.BSLS_ID__c ;
                        itemDto.placeOfDischarge = item.Place_of_Discharge__r.BSLS_ID__c ;
                        itemDto.equipmentType = item.Equipment_Type_Order__r.BSLS_ID__c ;
                        if(item.Agent__c != null){
                            Agent agentObj = new Agent();
                            agentObj.AgentName = item.Agent__r.Name;
                            agentObj.SFID = item.Agent__c;
                            agentObj.BSLSID = item.Agent__r.BSLS_ID__c;
                            itemDto.Agent = agentObj;
                        }
                        if(itemIdToConsigneeId.size() > 0 && itemIdToConsigneeId.containsKey(item.id)){
                            List<Consignee> consigneeDtoList = new List<Consignee>();
                            for(Consignee__c consObj : itemIdToConsigneeId.get(item.id)){
                                Consignee dtoObj = new Consignee();
                                dtoObj.AccountName = consObj.Consignee__r.Name;
                                dtoObj.Branch  = consObj.Consignee__r.Branch__c;
                                dtoObj.AccountOwner  = consObj.Consignee__r.Owner.name;
                                dtoObj.BillingAddress  = String.valueOf(consObj.Consignee__r.BillingAddress);
                                dtoObj.SFID  = consObj.id;
                                dtoObj.BSLSID  = consObj.Consignee__r.BSLS_ID__c;
                                consigneeDtoList.add(dtoObj);
                            }
                            itemDto.Consignee = consigneeDtoList;
                        }
                        if(itemIdToShipperId.size() > 0 && itemIdToShipperId.containsKey(item.id)){
                            List<Shipper> shipperDtoList = new List<Shipper>();
                            for(Shipper__c shipObj : itemIdToShipperId.get(item.Id)){
                                Shipper dtoObj = new Shipper();
                                dtoObj.AccountName = shipObj.Shipper__r.Name;
                                dtoObj.Branch  = shipObj.Shipper__r.Branch__c;
                                dtoObj.AccountOwner  = shipObj.Shipper__r.Owner.name;
                                dtoObj.BillingAddress  = String.valueOf(shipObj.Shipper__r.BillingAddress);
                                dtoObj.SFID  = shipObj.id;
                                dtoObj.BSLSID  = shipObj.Shipper__r.BSLS_ID__c;
                                shipperDtoList.add(dtoObj);
                            }
                            itemDto.Shipper = shipperDtoList;
                        }
                        orderItemDtoList.add(itemDto);
                    }
                    orderDto.orderItemList = orderItemDtoList;
                }
                dto.OrderObj = orderDto;
                orderDtoList.add(dto);
                system.debug('orderDtoList'+orderDtoList);
            }
        }
        OrderDetails dtoObj = new OrderDetails();
        dtoObj.OrderList = orderDtoList;
        //returnResult = JSON.serialize(dtoObj);
        system.debug('returnResult'+returnResult);
        return dtoObj;
    }
    public class OrderDetails{
        @AuraEnabled public List<OrderList> OrderList {get;Set;}
    }
    public class OrderList{
        @AuraEnabled public AccountObj  AccountObj{get;set;}
        @AuraEnabled public OrderObj  OrderObj{get;set;}
    }
    public class AccountObj{
        @AuraEnabled public String AccountName {get;Set;}
        @AuraEnabled public String Branch {get;Set;}
        @AuraEnabled public String AccountOwner {get;Set;}
        @AuraEnabled public String BillingAddress {get;Set;}
        @AuraEnabled public String SFID {get;Set;}
        @AuraEnabled public String BSLSID {get;Set;}
    }
    public class OrderObj{
        @AuraEnabled public String OrderNumber {get;Set;}
        @AuraEnabled public String QuotationNumber {get;Set;}
        @AuraEnabled public Date QuotationValidity {get;Set;}
        @AuraEnabled public Date OrderValidity {get;Set;}
        @AuraEnabled public List<OrderItemList> orderItemList {get;Set;}
    }
    public class OrderItemList{
        @AuraEnabled public String OrderNumber {get;Set;}
        @AuraEnabled public String OrderItemNumber {get;Set;}
        @AuraEnabled public String opsExecutive {get;Set;}
        @AuraEnabled public String shippingline {get;Set;}
        @AuraEnabled public String portOfLoading {get;Set;}
        @AuraEnabled public String portOfDestination {get;Set;}
        @AuraEnabled public String placeOfPickup {get;Set;}
        @AuraEnabled public String placeOfDischarge {get;Set;}
        @AuraEnabled public String equipmentType {get;Set;}
        @AuraEnabled public Integer serviceType {get;Set;}
        @AuraEnabled public Integer shipmentType {get;Set;}
        @AuraEnabled public Agent Agent {get;Set;}
        @AuraEnabled public List<Consignee> Consignee {get;Set;}
        @AuraEnabled public List<Shipper> Shipper {get;Set;}
    }
    public class Agent{
        @AuraEnabled public String AgentName {get;Set;}
        @AuraEnabled public String SFID {get;Set;}
        @AuraEnabled public String BSLSID {get;Set;}
    }
    public class Consignee{
        @AuraEnabled public String AccountName {get;Set;}
        @AuraEnabled public String Branch {get;Set;}
        @AuraEnabled public String AccountOwner {get;Set;}
        @AuraEnabled public String BillingAddress {get;Set;}
        @AuraEnabled public String SFID {get;Set;}
        @AuraEnabled public String BSLSID {get;Set;}
    }
    public class Shipper{
        @AuraEnabled public String AccountName {get;Set;}
        @AuraEnabled public String Branch {get;Set;}
        @AuraEnabled public String AccountOwner {get;Set;}
        @AuraEnabled public String BillingAddress {get;Set;}
        @AuraEnabled public String SFID {get;Set;}
        @AuraEnabled public String BSLSID {get;Set;}
    }
}