force-app/main/default/objects/Account/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Modes__c.field-meta.xml
<CustomField>
    <fullName>Modes__c</fullName>
    <label>Modes</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Modes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Leadc__c.field-meta.xml
<CustomField>
    <fullName>Leadc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Leadc</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Leadc</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Modes__c.field-meta.xml
<CustomField>
    <fullName>Modes__c</fullName>
    <label>Modes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Modes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Business_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Import</fullName>
    </customValue>
    <customValue>
        <fullName>Export</fullName>
    </customValue>
    <masterLabel>Business Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Modes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Sea</fullName>
    </customValue>
    <customValue>
        <fullName>Land</fullName>
    </customValue>
    <customValue>
        <fullName>Air</fullName>
    </customValue>
    <masterLabel>Modes</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BAFCOLeadDetailsHelper.cls
public class BAFCOLeadDetailsHelper {
    public static List<Lead__c> getLeadDetails(String leadId){         
        return [Select id,Name,Status__c,CreatedDate, Modes__c, Business_Type__c,owner.name From Lead__c Where id =: leadId limit 1];
    }
    public static List<contact> getContactDetails(String leadId){
        return [Select MobilePhone,Email from Contact where Leadc__c =: leadId order by createddate limit 1];
    }
    public static List<Account> getAccountDetails(String leadId){         
        return [Select id,Name,owner.name,CreatedDate From Account Where id =: leadId limit 1];
    }
    public static List<contact> getAccountContactDetails(String leadId){
        return [Select MobilePhone,Email from Contact where AccountId =: leadId order by createddate limit 1];
    }
}