force-app/main/default/objects/Commodity__c/Commodity__c.object-meta.xml
<CustomObject>
    <label>Commodity</label>
    <nameField>
        <label>Commodity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commodities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Commodity__c/fields/DG_Class__c.field-meta.xml
<CustomField>
    <fullName>DG_Class__c</fullName>
    <label>DG Class</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Equipment_Type__c/Equipment_Type__c.object-meta.xml
<CustomObject>
    <label>Equipment Type</label>
    <nameField>
        <label>Equipment Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipment Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/INCO_Term__c/INCO_Term__c.object-meta.xml
<CustomObject>
    <label>INCO Term</label>
    <nameField>
        <label>INCO Term</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>INCO Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Commercial_User__c.field-meta.xml
<CustomField>
    <fullName>Commercial_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commercial User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Commercial Profile</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Records_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Port__c/Port__c.object-meta.xml
<CustomObject>
    <label>Port</label>
    <nameField>
        <label>Port Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <displayFormat>ROT-{0000}</displayFormat>
        <label>Route Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/fields/Cargo_Weight__c.field-meta.xml
<CustomField>
    <fullName>Cargo_Weight__c</fullName>
    <label>Cargo Weight</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Route__c/fields/Commodity__c.field-meta.xml
<CustomField>
    <fullName>Commodity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commodity</label>
    <referenceTo>Commodity__c</referenceTo>
    <relationshipLabel>Routes</relationshipLabel>
    <relationshipName>Routes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route__c/fields/Dangerous_Goods__c.field-meta.xml
<CustomField>
    <fullName>Dangerous_Goods__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dangerous Goods</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Route__c/fields/DG_Class__c.field-meta.xml
<CustomField>
    <fullName>DG_Class__c</fullName>
    <label>DG Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Class 1</fullName>
            </value>
            <value>
                <fullName>Class 2</fullName>
            </value>
            <value>
                <fullName>Class 3</fullName>
            </value>
            <value>
                <fullName>Class 4</fullName>
            </value>
            <value>
                <fullName>Class 5</fullName>
            </value>
            <value>
                <fullName>Class 6</fullName>
            </value>
            <value>
                <fullName>Class 7</fullName>
            </value>
            <value>
                <fullName>Class 8</fullName>
            </value>
            <value>
                <fullName>Class 9</fullName>
            </value>
            <value>
                <fullName>Class 10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Route__c/fields/INCO_Term__c.field-meta.xml
<CustomField>
    <fullName>INCO_Term__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>INCO Term</label>
    <referenceTo>INCO_Term__c</referenceTo>
    <relationshipLabel>Routes</relationshipLabel>
    <relationshipName>Routes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route__c/fields/Opportunity_Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Enquiry__c</fullName>
    <label>Opportunity Enquiry</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Routes</relationshipLabel>
    <relationshipName>Routes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Route__c/fields/Pickup_Place__c.field-meta.xml
<CustomField>
    <fullName>Pickup_Place__c</fullName>
    <label>Pickup Place</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Route__c/fields/Place_of_Pickup__c.field-meta.xml
<CustomField>
    <fullName>Place_of_Pickup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Place of Pickup</label>
    <referenceTo>Place__c</referenceTo>
    <relationshipLabel>Routes</relationshipLabel>
    <relationshipName>Routes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route__c/fields/Port_of_Destination__c.field-meta.xml
<CustomField>
    <fullName>Port_of_Destination__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Port of Destination</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipLabel>Routes (Port of Destination)</relationshipLabel>
    <relationshipName>Routes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route__c/fields/Port_of_loading__c.field-meta.xml
<CustomField>
    <fullName>Port_of_loading__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Port of loading</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipLabel>Routes</relationshipLabel>
    <relationshipName>Routes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route__c/fields/Regular_Routing_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Regular_Routing_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Regular Routing Lookup</label>
    <referenceTo>Regular_Routing__c</referenceTo>
    <relationshipLabel>Routes</relationshipLabel>
    <relationshipName>Routes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route__c/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>P2P</fullName>
            </value>
            <value>
                <fullName>D2P</fullName>
            </value>
            <value>
                <fullName>P2D</fullName>
            </value>
            <value>
                <fullName>D2D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Route__c/fields/Shipping_Line__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Line</label>
    <referenceTo>Shipping_Line__c</referenceTo>
    <relationshipLabel>Routes</relationshipLabel>
    <relationshipName>Routes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route_Equipment__c/Route_Equipment__c.object-meta.xml
<CustomObject>
    <label>Route Equipment</label>
    <nameField>
        <displayFormat>REQ-{00000}</displayFormat>
        <label>Route Equipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Route Equipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Route_Equipment__c/fields/Equipment_Type__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment Type</label>
    <referenceTo>Equipment_Type__c</referenceTo>
    <relationshipName>Enquiry_Equipments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route_Equipment__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Route_Equipment__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Route Equipments</relationshipLabel>
    <relationshipName>Route_Equipments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Shipping_Line__c/Shipping_Line__c.object-meta.xml
<CustomObject>
    <label>Shipping Line</label>
    <nameField>
        <label>Shipping Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipping Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Business_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Import</fullName>
    </customValue>
    <customValue>
        <fullName>Export</fullName>
    </customValue>
    <masterLabel>Business Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BAFCOEditOpportunityController.cls
public class BAFCOEditOpportunityController {
    @AuraEnabled 
    public static string getAccountId(String optyId){
        return [Select AccountId from Opportunity where id =: optyId].AccountId;
    }
    @AuraEnabled public static OptyDetails getEditOptyDetail(String optyId){
        Opportunity opty = [Select id,CloseDate,Commercial_User__r.Name,Business_Type__c from Opportunity where id =:optyId ];
        OptyDetails dto = new OptyDetails();
        dto.businessType = opty.Business_Type__c;
        dto.closeDate = opty.CloseDate;
        dto.commercialUserId = opty.Commercial_User__c;
        dto.commercialUserName = opty.Commercial_User__r.name;
        Integer routeIndex = 1;
        List<BAFCORoutingDetailsDto> routingList = new List<BAFCORoutingDetailsDto>();
        for(Route__c routeObj : [Select Pickup_Place__c,(Select id,Quantity__c,Equipment_Type__r.name from Route_Equipments__r),Regular_Routing_Lookup__c,Discharge_Place__c,Place_of_Pickup__c,Dangerous_Goods__c,Remarks__c,id,Commodity__r.name,INCO_Term__r.name,Cargo_Weight__c,DG_Class__c,Port_of_loading__r.name,Port_of_Destination__r.name,Shipping_Line__r.name,Service_Type__c from Route__c where Opportunity_Enquiry__c =: optyId]){
            BAFCORoutingDetailsDto routeDto = new BAFCORoutingDetailsDto();
            routeDto.routeName = 'Route '+routeIndex;
            if(routeObj.Commodity__c != null){
                routeDto.commodity = routeObj.Commodity__c;
                routeDto.commodityName = routeObj.Commodity__r.name;
            }
            if(routeObj.INCO_Term__c != null){
                routeDto.incoTerm = routeObj.INCO_Term__c;
                routeDto.incoTermName = routeObj.INCO_Term__r.name;
            }
            if(routeObj.Port_of_loading__c != null){
                routeDto.portLoadingId = routeObj.Port_of_loading__c;
                routeDto.portLoading = routeObj.Port_of_loading__r.name;
            }
            if(routeObj.Port_of_Destination__c != null){
                routeDto.portDestinationId = routeObj.Port_of_Destination__c;
                routeDto.portDestination = routeObj.Port_of_Destination__r.name;
            }
            if(routeObj.Shipping_Line__c != null){
                routeDto.shippingLine = routeObj.Shipping_Line__c;
                routeDto.shippingLineName = routeObj.Shipping_Line__r.Name;
            }
            routeDto.leadIndex = String.valueOf(routeIndex);
            routeDto.serviceType = routeObj.Service_Type__c;
            routeDto.remarks = routeObj.Remarks__c;
            routeDto.cargoWeights = routeObj.Cargo_Weight__c;
            routeDto.dangerousGoods = routeObj.Dangerous_Goods__c;
            routeDto.dgClass = routeobj.DG_Class__c;
            routeDto.placeOfPickup = routeObj.Pickup_Place__c;
            routeDto.placeOfDischarge = routeObj.Discharge_Place__c;
            routeDto.routeId = routeObj.id;
            routeDto.routingRegular = routeObj.Regular_Routing_Lookup__c;
            List<BAFCORoutingDetailsDto.containerRecord> containerList = new List<BAFCORoutingDetailsDto.containerRecord>();
            if(routeObj.Route_Equipments__r.size() > 0){
                Integer containerIndex = 1;
                for(Route_Equipment__c item : routeObj.Route_Equipments__r){
                    BAFCORoutingDetailsDto.containerRecord itemDto = new BAFCORoutingDetailsDto.containerRecord();
                    itemDto.containerType = item.Equipment_Type__c;
                    itemDto.containerTypeName = item.Equipment_Type__r.name;
                    itemDto.quantity = item.Quantity__c;
                    itemDto.id = item.id;
                    itemDto.index = String.valueOf(routeIndex)+'.'+String.valueOf(containerIndex++);
                    containerList.add(itemDto);
                }
            }
            routeDto.containerRecord = containerList;
            routeIndex++;
            routingList.add(routeDto);
        }
        dto.routingList = routingList;
        return dto;
    }
    public class OptyDetails{
        @AuraEnabled public string businessType{get;set;}
        @AuraEnabled public date closeDate{get;set;}
        @AuraEnabled public String commercialUserId{get;set;}
        @AuraEnabled public String commercialUserName{get;set;}
        @AuraEnabled public List<BAFCORoutingDetailsDto> routingList{get;set;}
    }
}