force-app/main/default/objects/Opportunity/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <formula>TEXT(Owner.Branch__c)</formula>
    <label>Branch</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>ORD-{MM}/{YY}-{000}</displayFormat>
        <label>Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <formula>TEXT( Quotation__r.Opportunity__r.Owner.Branch__c )</formula>
    <label>Branch</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Opportunity_Order__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Order</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Confirmed</fullName>
                <default>true</default>
                <label>Confirmed</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>CRO Amendment Awaited</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Target</label>
    <referenceTo>Target__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Total_Teus__c.field-meta.xml
<CustomField>
    <fullName>Total_Teus__c</fullName>
    <label>Total Teus</label>
    <summarizedField>Order_Item__c.Teus_FB__c</summarizedField>
    <summaryForeignKey>Order_Item__c.Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Target__c/Target__c.object-meta.xml
<CustomObject>
    <label>Target</label>
    <nameField>
        <label>Target Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Target__c/fields/Achieved_Value_In_Teus__c.field-meta.xml
<CustomField>
    <fullName>Achieved_Value_In_Teus__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Achieved Value (In Teus)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Target__c/fields/Month_Value__c.field-meta.xml
<CustomField>
    <fullName>Month_Value__c</fullName>
    <formula>MONTH(Target_Month__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Month Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Target__c/fields/Target_Month__c.field-meta.xml
<CustomField>
    <fullName>Target_Month__c</fullName>
    <label>Target Month</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Target__c/fields/Target_Value_In_Teus__c.field-meta.xml
<CustomField>
    <fullName>Target_Value_In_Teus__c</fullName>
    <label>Target Value (In Teus)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Target__c/fields/Year_Value__c.field-meta.xml
<CustomField>
    <fullName>Year_Value__c</fullName>
    <formula>Year(Target_Month__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BAFCOOrderTriggerHandler.cls
public class BAFCOOrderTriggerHandler {
    public static void beforeAction(List<Order__c> orderList){
        system.debug('orderList'+orderList);
        set<Id> orderIDSet = new set<Id>();
        set<Id> opportunityIDSet = new set<Id>();
        Map<ID,String> oppOwnerMap = new Map<ID,String>();
        Map<Id,Id> targetOwnerMap = new Map<Id,Id>();
        for(Order__c ordRec:orderList){
            opportunityIDSet.add(ordRec.Opportunity_Order__c);
        }
        system.debug('opportunityIDSet'+opportunityIDSet);
        for(Opportunity oppOwners : [Select Id,OwnerID FROM Opportunity where ID IN : opportunityIDSet]){
            oppOwnerMap.put(oppOwners.ID,oppOwners.OwnerID);
        }
        system.debug('oppOwnerMap'+oppOwnerMap);
        Date dt = System.today();
        Integer currentMonth = dt.Month();
        Integer currentYear = dt.Year();
        
        for(Target__c targetRec : [Select ID,Target_Value_In_Teus__c,Achieved_Value_In_Teus__c,Target_Month__c,OwnerId,Year_Value__c,Month_Value__c FROM Target__c 
                                   Where OwnerId IN:oppOwnerMap.values()
                                   AND Month_Value__c=:currentMonth AND Year_Value__c=:currentYear]){
                                       targetOwnerMap.put(targetRec.OwnerId,targetRec.Id);  
                                   }
        system.debug('targetOwnerMap'+targetOwnerMap);
        for(Order__c ordRec:orderList){
            ordRec.Target__c = targetOwnerMap.get(oppOwnerMap.get(ordRec.Opportunity_Order__c));  
        }
        system.debug('orderList'+orderList);
        
    }
    public static void updateOrderName(List<Order__c> newList){
        system.debug('newList'+newList);
        List<Order__c> jubailRecord = [Select ID,Record_Number__c,Name,Branch__c from Order__c Where Branch__c='Jubail' AND Record_Number__c!=NULL order by Record_Number__c DESC ];
        List<Order__c> jeddahRecord = [Select ID,Record_Number__c,Name,Branch__c from Order__c Where Branch__c='Jeddah' AND Record_Number__c!=NULL order by Record_Number__c DESC ];
        List<Order__c> riyadRecord =  [Select ID,Record_Number__c,Name,Branch__c from Order__c Where Branch__c='Riyadh' AND Record_Number__c!=NULL order by Record_Number__c DESC ];
        List<Order__c> dammamRecord = [Select ID,Record_Number__c,Name,Branch__c from Order__c Where Branch__c='Dammam' AND Record_Number__c!=NULL order by Record_Number__c DESC ];
        
        for(Order__c newOrder : newList){
            if(newOrder.Branch__c!=NULL){
                Decimal latestNumber;
                if(newOrder.Branch__c=='Jubail'){
                    if(jubailRecord.size()>0){                        
                        system.debug('In jubailRecord');
                        latestNumber=jubailRecord[0].Record_Number__c;
                        if(newOrder.Record_Number__c!=NULL){
                            newOrder.Record_Number__c=newOrder.Record_Number__c+1;
                        }
                        else{
                            newOrder.Record_Number__c=1;
                        }
                        newOrder.Name =getLatestNameValue(latestNumber,'JUB','O');                        
                        
                    }else{
                        String yearVal = String.valueOf(system.today().year()).right(2);
                        newOrder.Name ='JUB/O/'+yearVal+'/1';
                        newOrder.Record_Number__c=1;
                    }
                }
                else if(newOrder.Branch__c=='Jeddah'){
                    if(jeddahRecord.size()>0){                        
                        system.debug('In jeddahRecord');
                        latestNumber=jeddahRecord[0].Record_Number__c;
                        if(newOrder.Record_Number__c!=NULL){
                            newOrder.Record_Number__c=newOrder.Record_Number__c+1;
                        }
                        else{
                            newOrder.Record_Number__c=1;
                        }
                        newOrder.Name =getLatestNameValue(latestNumber,'JED','O');                        
                        
                    }else{
                        String yearVal = String.valueOf(system.today().year()).right(2);
                        newOrder.Name ='JED/O/'+yearVal+'/1';
                        newOrder.Record_Number__c=1;
                    }
                }
                
                else if(newOrder.Branch__c=='Riyadh'){
                    if(riyadRecord.size()>0){                        
                        system.debug('In riyadRecord');
                        latestNumber=riyadRecord[0].Record_Number__c;
                        if(newOrder.Record_Number__c!=NULL){
                            newOrder.Record_Number__c=newOrder.Record_Number__c+1;
                        }
                        else{
                            newOrder.Record_Number__c=1;
                        }
                        newOrder.Name =getLatestNameValue(latestNumber,'RYD','O');                        
                        
                    }else{
                        String yearVal = String.valueOf(system.today().year()).right(2);
                        newOrder.Name ='RYD/O/'+yearVal+'/1';
                        newOrder.Record_Number__c=1;
                    }
                }
                
                else if(newOrder.Branch__c=='Dammam'){
                    if(dammamRecord.size()>0){                        
                        system.debug('In dammamRecord');
                        latestNumber=dammamRecord[0].Record_Number__c;
                        if(newOrder.Record_Number__c!=NULL){
                            newOrder.Record_Number__c=newOrder.Record_Number__c+1;
                        }
                        else{
                            newOrder.Record_Number__c=1;
                        }
                        newOrder.Name =getLatestNameValue(latestNumber,'DMM','O');                        
                        
                    }else{
                        String yearVal = String.valueOf(system.today().year()).right(2);
                        newOrder.Name ='DMM/O/'+yearVal+'/1';
                        newOrder.Record_Number__c=1;
                    }
                }  
            }               
        }
    }
    
    public static String getLatestNameValue(Decimal latestNumber,String BranchCode,String recordType){
        String latestValue;
        String yearVal = String.valueOf(system.today().year()).right(2);
        //latestNumber = latestNumber.right(4);
        system.debug('latestNumber'+latestNumber);
        //Integer latestNumberVal = Integer.valueOf(latestNumber) + 1;
        Decimal latestNumberVal = latestNumber+1;
        system.debug('latestNumberVal : '+latestNumberVal);
        
        latestValue = BranchCode+'/'+recordType+'/'+yearVal+'/'+latestNumberVal;
        system.debug('latestValue : '+latestValue);
        return latestValue;        
    }
    
    public static void afterAction(List<Order__c> orderList){
        set<ID> orderIDSet = new Set<ID>();
        List<ID> orderIDList = new List<ID>();
        for(Order__c ord:orderList){
            orderIDSet.add(ord.ID);
        }
        orderIDList.addAll(orderIDSet);
        BAFCOSendOrdersAPI.sendOrderData(orderIDList);        
    }
    
    public static void updateTargetData(List<Order__c> orderList){
        Set<ID> orderIDSet = new Set<ID>();
        Set<ID> targetIdSet = new Set<ID>();
        Map<ID,Decimal> targetValueMap = new Map<ID, Decimal>();
        List<Target__c> targetsListToUpdate = new List<Target__c>();
        for(Order__c ord:orderList){
            orderIDSet.add(ord.ID);
            targetIdSet.add(ord.Target__c);
        }
        AggregateResult[] groupedResult = [Select Target__c, Sum(Total_Teus__c) FROM Order__c 
                                           WHERE Target__c!=NULL AND Target__c IN: targetIdSet AND Status__c!='Cancelled' 
                                           Group by Target__c];
        for(AggregateResult ar:groupedResult){
            targetValueMap.put((Id)ar.get('Target__c'),(decimal)ar.get('expr0'));
        }
        system.debug('targetValueMap'+targetValueMap);
        for(Target__c trg:[Select ID,Target_Value_In_Teus__c,Achieved_Value_In_Teus__c,Target_Month__c,OwnerId,Year_Value__c,Month_Value__c 
                           FROM Target__c 
                           Where Id IN:targetValueMap.Keyset()]){
                               if(targetValueMap.get(trg.Id)!=NULL){
                                   trg.Achieved_Value_In_Teus__c = targetValueMap.get(trg.Id);
                                   targetsListToUpdate.add(trg);
                               }
                           }
        if(targetsListToUpdate!=NULL){
            database.update(targetsListToUpdate);
        }
    }
}