force-app/main/default/objects/Agent__c/Agent__c.object-meta.xml
<CustomObject>
    <label>Agent</label>
    <nameField>
        <label>Agent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipment_Type__c/Equipment_Type__c.object-meta.xml
<CustomObject>
    <label>Equipment Type</label>
    <nameField>
        <label>Equipment Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipment Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rate_Procurement__c/Rate_Procurement__c.object-meta.xml
<CustomObject>
    <label>Rate Procurement</label>
    <nameField>
        <label>Procurement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rates Procurement</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rate_Procurement__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent</label>
    <referenceTo>Agent__c</referenceTo>
    <relationshipLabel>Rates Procurement</relationshipLabel>
    <relationshipName>Rates_Procurement</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rate_Procurement__c/fields/Equipment_Type__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment Type</label>
    <referenceTo>Equipment_Type__c</referenceTo>
    <relationshipLabel>Rates Procurement</relationshipLabel>
    <relationshipName>Rates_Procurement</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rate_Procurement__c/fields/Port_of_Discharge__c.field-meta.xml
<CustomField>
    <fullName>Port_of_Discharge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Port of Discharge</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipLabel>Rates Procurement (Port of Discharge)</relationshipLabel>
    <relationshipName>Rates_Procurement1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rate_Procurement__c/fields/Port_of_Loading__c.field-meta.xml
<CustomField>
    <fullName>Port_of_Loading__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Port of Loading</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipLabel>Rates Procurement</relationshipLabel>
    <relationshipName>Rates_Procurement</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rate_Procurement__c/fields/RMS__c.field-meta.xml
<CustomField>
    <fullName>RMS__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RMS</label>
    <referenceTo>RMS__c</referenceTo>
    <relationshipLabel>Rates Procurement</relationshipLabel>
    <relationshipName>Rates_Procurement</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rate_Procurement__c/fields/Shipping_Line__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Line</label>
    <referenceTo>Shipping_Line__c</referenceTo>
    <relationshipLabel>Rates Procurement</relationshipLabel>
    <relationshipName>Rates_Procurement</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rate_Procurement__c/recordTypes/Received.recordType-meta.xml
<RecordType>
    <fullName>Received</fullName>
    <active>true</active>
    <label>Received</label>
</RecordType>

force-app/main/default/objects/RMS__c/RMS__c.object-meta.xml
<CustomObject>
    <label>RMS</label>
    <nameField>
        <label>RMS Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent</label>
    <referenceTo>Agent__c</referenceTo>
    <relationshipLabel>RMS</relationshipLabel>
    <relationshipName>RMS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RMS__c/fields/Equipment_Type__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Equipment Type</label>
    <referenceTo>Equipment_Type__c</referenceTo>
    <relationshipLabel>RMS</relationshipLabel>
    <relationshipName>RMS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RMS__c/fields/Port_Of_Discharge__c.field-meta.xml
<CustomField>
    <fullName>Port_Of_Discharge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Port Of Discharge</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipLabel>RMS (Port Of Discharge)</relationshipLabel>
    <relationshipName>RMS1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RMS__c/fields/Port_Of_Loading__c.field-meta.xml
<CustomField>
    <fullName>Port_Of_Loading__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Port Of Loading</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipLabel>RMS</relationshipLabel>
    <relationshipName>RMS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RMS__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>RMS</relationshipLabel>
    <relationshipName>RMS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RMS__c/fields/Route_Equipment__c.field-meta.xml
<CustomField>
    <fullName>Route_Equipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route Equipment</label>
    <referenceTo>Route_Equipment__c</referenceTo>
    <relationshipLabel>RMS</relationshipLabel>
    <relationshipName>RMS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RMS__c/fields/Shipping_Line__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Line</label>
    <referenceTo>Shipping_Line__c</referenceTo>
    <relationshipLabel>RMS</relationshipLabel>
    <relationshipName>RMS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RMS__c/recordTypes/Export.recordType-meta.xml
<RecordType>
    <fullName>Export</fullName>
    <active>true</active>
    <label>Export</label>
</RecordType>

force-app/main/default/objects/RMS__c/recordTypes/Import.recordType-meta.xml
<RecordType>
    <fullName>Import</fullName>
    <active>true</active>
    <label>Import</label>
</RecordType>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <displayFormat>ROT-{0000}</displayFormat>
        <label>Route Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/fields/Chargeable_Weight__c.field-meta.xml
<CustomField>
    <fullName>Chargeable_Weight__c</fullName>
    <formula>IF( Total_Gross_Weight_KGs__c &gt;  Total_Volumetric_Weight__c , Total_Gross_Weight_KGs__c , Total_Volumetric_Weight__c )</formula>
    <label>Chargeable Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Route__c/fields/Port_of_Destination__c.field-meta.xml
<CustomField>
    <fullName>Port_of_Destination__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Port of Destination</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipLabel>Routes (Port of Destination)</relationshipLabel>
    <relationshipName>Routes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route__c/fields/Port_of_loading__c.field-meta.xml
<CustomField>
    <fullName>Port_of_loading__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Port of loading</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipLabel>Routes</relationshipLabel>
    <relationshipName>Routes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route__c/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>P2P</fullName>
            </value>
            <value>
                <fullName>D2P</fullName>
            </value>
            <value>
                <fullName>P2D</fullName>
            </value>
            <value>
                <fullName>D2D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Route__c/fields/Shipping_Line__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Line</label>
    <referenceTo>Shipping_Line__c</referenceTo>
    <relationshipLabel>Routes</relationshipLabel>
    <relationshipName>Routes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route__c/fields/Total_CBM__c.field-meta.xml
<CustomField>
    <fullName>Total_CBM__c</fullName>
    <label>Total CBM</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Route__c/fields/Total_Gross_Weight_KGs__c.field-meta.xml
<CustomField>
    <fullName>Total_Gross_Weight_KGs__c</fullName>
    <label>Total Gross Weight (KGs)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Route__c/fields/Total_Volumetric_Weight__c.field-meta.xml
<CustomField>
    <fullName>Total_Volumetric_Weight__c</fullName>
    <label>Total Volumetric Weight</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Route_Equipment__c/Route_Equipment__c.object-meta.xml
<CustomObject>
    <label>Route Equipment</label>
    <nameField>
        <displayFormat>REQ-{00000}</displayFormat>
        <label>Route Equipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Route Equipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Route_Equipment__c/fields/Chargeable_Weight__c.field-meta.xml
<CustomField>
    <fullName>Chargeable_Weight__c</fullName>
    <formula>IF( (CBM__c * 167)&gt;  Weight_Kgs__c , CBM__c , Weight_Kgs__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Chargeable Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Route_Equipment__c/fields/Equipment_Type__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment Type</label>
    <referenceTo>Equipment_Type__c</referenceTo>
    <relationshipName>Enquiry_Equipments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route_Equipment__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Route_Equipment__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Route Equipments</relationshipLabel>
    <relationshipName>Route_Equipments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Route_Equipment__c/fields/Tab_View__c.field-meta.xml
<CustomField>
    <fullName>Tab_View__c</fullName>
    <formula>IF( Route__r.Opportunity_Enquiry__r.RecordType.Name ==  &apos;Air Freight&apos;, &apos;Total CBM Weight :&apos;&amp; Text( Route__r.Total_CBM__c ) &amp;&apos; Total Gross Weight:&apos;&amp; Text( Route__r.Total_Gross_Weight_KGs__c ) &amp;&apos; Total Volumetric Weight : &apos;&amp; Text( Route__r.Total_Volumetric_Weight__c ), &apos;CBM : &apos;&amp; Text(CBM__c) &amp;&apos; | Weight : &apos;&amp; Text(Weight_Kgs__c) &amp;&apos; | Units : &apos;&amp;Text(Units__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tab View</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Route_Equipment__c/fields/Teusnew__c.field-meta.xml
<CustomField>
    <fullName>Teusnew__c</fullName>
    <label>Teusnew</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shipping_Line__c/Shipping_Line__c.object-meta.xml
<CustomObject>
    <label>Shipping Line</label>
    <nameField>
        <label>Shipping Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipping Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BAFCORouteEquipmentTriggerController.cls
public class BAFCORouteEquipmentTriggerController {
    public static final Id RMS_EXPORT_RECORDTYPE_Id = Schema.SObjectType.RMS__c.getRecordTypeInfosByName()
        .get('Export')
        .getRecordTypeId();
    public static final Id RMS_IMPORT_RECORDTYPE_Id = Schema.SObjectType.RMS__c.getRecordTypeInfosByName()
        .get('Import')
        .getRecordTypeId();
    public static void insertRouteProcumnet(List<Route_Equipment__c> newList){
        Set<Id> routeIds = new Set<Id>();
        Set<Id> loadingPortIds = new Set<Id>();
        Set<Id> destinationPortIds = new Set<Id>();
        Set<Id> shippingLineIds = new Set<Id>();
        Set<Id> equipmentIds = new Set<Id>();
        List<Rate_Procurement__c> ratePocumentList = new List<Rate_Procurement__c>();
        for(Route_Equipment__c routequip: newList){
            if(routequip.Equipment_Type__c != null) {
                routeIds.add(routequip.Route__c);
                if(routequip.Equipment_Type__c != null ) equipmentIds.add(routequip.Equipment_Type__c);
            }
        }
        for(Route__c routeObj : [Select id, Port_of_Destination__c,Port_of_loading__c,Shipping_Line__c from Route__c where id in : routeIds]){
            if(routeObj.Port_of_loading__c != null ) loadingPortIds.add(routeObj.Port_of_loading__c);
            if(routeObj.Port_of_Destination__c != null ) destinationPortIds.add(routeObj.Port_of_Destination__c);
            if(routeObj.Shipping_Line__c != null ) shippingLineIds.add(routeObj.Shipping_Line__c);
        }
        for(Rms__c rmsobj : [Select Agent__c,id,RecordTypeId,Port_Of_Loading__c,Port_Of_Discharge__c,Shipping_Line__c,Equipment_Type__c from Rms__c 
                             where Port_Of_Loading__c in : loadingPortIds AND Port_Of_Discharge__c in :  destinationPortIds
                             AND Shipping_Line__c in : shippingLineIds and Equipment_Type__c in : equipmentIds
                            ]){
                                List<Rate_Procurement__c> procumentList  = new  List<Rate_Procurement__c>();
                                if(rmsObj.RecordTypeId == RMS_EXPORT_RECORDTYPE_Id){
                                    procumentList = [Select id from Rate_Procurement__c where 
                                                     Port_of_Loading__c =:rmsobj.Port_Of_Loading__c AND 
                                                     Port_of_Discharge__c =:rmsObj.Port_Of_Discharge__c AND 
                                                     Shipping_Line__c =: rmsObj.Shipping_Line__c AND 
                                                     Equipment_Type__c =: rmsObj.Equipment_Type__c limit 1];
                                }
                                else if(rmsObj.RecordTypeId == RMS_IMPORT_RECORDTYPE_Id){
                                    procumentList = [Select id from Rate_Procurement__c where 
                                                     Port_of_Loading__c =:rmsobj.Port_Of_Loading__c AND 
                                                     Port_of_Discharge__c =:rmsObj.Port_Of_Discharge__c AND 
                                                     Shipping_Line__c =: rmsObj.Shipping_Line__c AND 
                                                     Agent__c =:rmsObj.Agent__c AND 
                                                     Equipment_Type__c =: rmsObj.Equipment_Type__c limit 1];
                                }
                                if(procumentList.size() > 0){
                                    Id ReceivedRecordtypeId = Schema.SObjectType.Rate_Procurement__c.getRecordTypeInfosByName()
                                        .get('Received')
                                        .getRecordTypeId();
                                    Rate_Procurement__c proobj = procumentList[0];
                                    proobj.RMS__c = rmsObj.id;
                                    proobj.RecordTypeId = ReceivedRecordtypeId;
                                    ratePocumentList.add(proobj);
                                }
                            }
        if(ratePocumentList.size()>0) update ratePocumentList;
    }
    public static void onbeforeInsert(List<Route_Equipment__c> newList){
        List<Id> routeIds = new List<Id>();
        Map<Id,Route__c> routeIdMap = new Map<Id,Route__c>();
        for(Route_Equipment__c rEquip : newList){
            routeIds.add(rEquip.Route__c);
        }
        for(Route__c routeObj : [Select id,Service_Type__c,Total_Gross_Weight_KGs__c,Total_CBM__c,Total_Volumetric_Weight__c from Route__c where id  in : routeIds]){
            routeIdMap.put(routeObj.id, routeObj);
        }
        for(Route_Equipment__c item : newList){
            if(routeIdMap.get(item.Route__c).Service_Type__c == 'Sea Export' || routeIdMap.get(item.Route__c).Service_Type__c == 'Sea Import' ||routeIdMap.get(item.Route__c).Service_Type__c == 'ISO Export' ||routeIdMap.get(item.Route__c).Service_Type__c == 'ISO Import'){
                if(item.Name.contains('40') == true){
                    item.Teusnew__c = 2 * (item.Quantity__c != null ? item.Quantity__c : 1);
                }
                if(item.Name.contains('20') == true){
                    item.Teusnew__c = 1 * (item.Quantity__c != null ? item.Quantity__c : 1);
                }
            }
            else if(routeIdMap.get(item.Route__c).Service_Type__c == 'Local Operation Export' || routeIdMap.get(item.Route__c).Service_Type__c == 'Local Operation Import'){
                if(item.Name.contains('40') == true){
                    item.Teusnew__c = item.Quantity__c > 0 ? item.Quantity__c/2 : 0;
                }
                if(item.Name.contains('20') == true){
                    item.Teusnew__c = item.Quantity__c > 0 ? item.Quantity__c/4 : 0;
                }
            }
            else if(routeIdMap.get(item.Route__c).Service_Type__c == 'LCL Export' || routeIdMap.get(item.Route__c).Service_Type__c == 'LCL Import'){
                Route__c routeObj = routeIdMap.get(item.Route__c);
                Decimal largest = 0;
                if(routeObj.Total_CBM__c >= routeObj.Total_Gross_Weight_KGs__c && routeObj.Total_CBM__c >= routeObj.Total_Volumetric_Weight__c){
                    largest = routeObj.Total_CBM__c ;
                }
                else if(routeObj.Total_Gross_Weight_KGs__c >= routeObj.Total_CBM__c && routeObj.Total_Gross_Weight_KGs__c >= routeObj.Total_Volumetric_Weight__c){
                    largest = routeObj.Total_Gross_Weight_KGs__c ;
                }
                else{
                    largest =  routeObj.Total_Volumetric_Weight__c;
                }
                item.Teusnew__c = largest > 0 ? largest / 250 : 0;
                /*if(routeEquipIdMap.containsKey(item.Tab_View__c)){
                    item.Teusnew__c = routeEquipIdMap.get(item.Tab_View__c) / 250;
                }*/
            }
            else if(routeIdMap.get(item.Route__c).Service_Type__c == 'Air Export' || routeIdMap.get(item.Route__c).Service_Type__c == 'Air Import'){
                item.Teusnew__c = (routeIdMap.get(item.Route__c).Chargeable_Weight__c)/250;
            }
        }
    }
}