force-app/main/default/objects/Contact/fields/Leadc__c.field-meta.xml
<CustomField>
    <fullName>Leadc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Leadc</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Leadc</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Business_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Import</fullName>
    </customValue>
    <customValue>
        <fullName>Export</fullName>
    </customValue>
    <masterLabel>Business Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BAFCOLeadDetailsControllerTest.cls
@isTest
public class BAFCOLeadDetailsControllerTest {
    @TestSetup
    static void setup() {
        Lead__c ld = new Lead__c();
        ld.Business_Type__c = 'Import';
        insert ld;
        
        Lead__c ld1 = new Lead__c();
        ld1.Business_Type__c = 'Export';
        insert ld1;
        
        Contact cont = new Contact();
        cont.FirstName='First Name';
        cont.LastName = 'Last name';
        cont.Leadc__c = ld.Id;
        insert cont;
    }
    testmethod static void getLeadDetailsTest01(){
        Id leadId = [Select id from Lead__c where Business_Type__c = 'Import' limit 1].Id;
        test.startTest();
        try{
        	BAFCOLeadDetailsController.getLeadDetails(leadId);
        }
        Catch(Exception e){
            System.debug('BAFCOLeadDetailsControllerTest.getLeadDetailsTest01 exception '+e);
        }
        test.stopTest();
    }
    testmethod static void getLeadDetailsTest02(){
        Id leadId = [Select id from Lead__c where Business_Type__c = 'Export' limit 1].Id;
        test.startTest();
        try{
        	BAFCOLeadDetailsController.getLeadDetails(leadId);
        }
        Catch(Exception e){
            System.debug('BAFCOLeadDetailsControllerTest.getLeadDetailsTest02 exception '+e);
        }
        test.stopTest();
    }
}