force-app/main/default/objects/Exchange_Rate__c/Exchange_Rate__c.object-meta.xml
<CustomObject>
    <label>Exchange Rate</label>
    <nameField>
        <label>Currency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exchange Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exchange_Rate__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <label>Currency Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exchange_Rate__c/fields/Exchange_Rate__c.field-meta.xml
<CustomField>
    <fullName>Exchange_Rate__c</fullName>
    <label>Exchange Rate</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BAFCOExchangeRateSchedulerTest.cls
@isTest
public class BAFCOExchangeRateSchedulerTest {
	public static testMethod void testschedule() {
        Exchange_Rate__c exObj = new Exchange_Rate__c();
        exObj.Currency_Code__c = 'INR';
        exObj.Name = 'Indian Rupees';
        Insert exObj;
		Test.StartTest();
        Test.setMock(HttpCalloutMock.class, new BAFCOExchangeRateMockTest());
		BAFCOExchangeRateScheduler testsche = new BAFCOExchangeRateScheduler();
		String sch = '0 0 23 * * ?';
		system.schedule('Test status Check', sch, testsche );
		Test.stopTest();
	}
    public static testmethod void excpetionCase(){
        Exchange_Rate__c exObj = new Exchange_Rate__c();
        exObj.Currency_Code__c = 'INR';
        exObj.Name = 'Indian Rupees';
        Insert exObj;
        Test.StartTest();
        Test.setMock(HttpCalloutMock.class, new BAFCOExchangeRateMockTest());
		BAFCOExchangeRateScheduler testsche = new BAFCOExchangeRateScheduler();
		String sch = '0 0 23 * * ?';
        try{
		system.schedule('Test status Check', sch, testsche );
        }
        catch(exception e){}
		Test.stopTest();
    }
}