force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>ORD-{MM}/{YY}-{000}</displayFormat>
        <label>Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account_Order__c.field-meta.xml
<CustomField>
    <fullName>Account_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Opportunity_Order__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Order</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Target</label>
    <referenceTo>Target__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>Order Item-{0000}</displayFormat>
        <label>Order Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Pickup_Place__c.field-meta.xml
<CustomField>
    <fullName>Pickup_Place__c</fullName>
    <label>Pickup Place</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Place_of_Discharge__c.field-meta.xml
<CustomField>
    <fullName>Place_of_Discharge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Place of Discharge</label>
    <referenceTo>Place__c</referenceTo>
    <relationshipLabel>Order Items (Place of Discharge)</relationshipLabel>
    <relationshipName>Order_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Port_of_Discharge_Order__c.field-meta.xml
<CustomField>
    <fullName>Port_of_Discharge_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Port of Discharge</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Port_of_Loading_Order__c.field-meta.xml
<CustomField>
    <fullName>Port_of_Loading_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Port of Loading</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipLabel>Order Items1</relationshipLabel>
    <relationshipName>Order_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Shipping_Line__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Line</label>
    <referenceTo>Shipping_Line__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Teus__c.field-meta.xml
<CustomField>
    <fullName>Teus__c</fullName>
    <formula>Quantity__c *  Equipment_Type_Order__r.Teus__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Teus</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Regular_Routing__c/Regular_Routing__c.object-meta.xml
<CustomObject>
    <label>Regular Routing</label>
    <nameField>
        <label>Routing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regular Routings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Regular_Routing__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Regular Routings</relationshipLabel>
    <relationshipName>Regular_Routing</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Regular_Routing__c/fields/Place_of_Discharge__c.field-meta.xml
<CustomField>
    <fullName>Place_of_Discharge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Place of Discharge</label>
    <referenceTo>Place__c</referenceTo>
    <relationshipLabel>Regular Routings</relationshipLabel>
    <relationshipName>Regular_Routings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Regular_Routing__c/fields/Port_of_Destination__c.field-meta.xml
<CustomField>
    <fullName>Port_of_Destination__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Port of Destination</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipLabel>Regular Routings</relationshipLabel>
    <relationshipName>Regular_Routings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Regular_Routing__c/fields/Port_of_Loading__c.field-meta.xml
<CustomField>
    <fullName>Port_of_Loading__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Port of Loading</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipLabel>Regular Routings</relationshipLabel>
    <relationshipName>Regular_Routing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Regular_Routing__c/fields/Shipping_Line__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Line</label>
    <referenceTo>Shipping_Line__c</referenceTo>
    <relationshipLabel>Regular Routing</relationshipLabel>
    <relationshipName>Regular_Routing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Line__c/Shipping_Line__c.object-meta.xml
<CustomObject>
    <label>Shipping Line</label>
    <nameField>
        <label>Shipping Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipping Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Target__c/Target__c.object-meta.xml
<CustomObject>
    <label>Target</label>
    <nameField>
        <label>Target Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Target__c/fields/Achieved_Value_In_Teus__c.field-meta.xml
<CustomField>
    <fullName>Achieved_Value_In_Teus__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Achieved Value (In Teus)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Target__c/fields/Month_Value__c.field-meta.xml
<CustomField>
    <fullName>Month_Value__c</fullName>
    <formula>MONTH(Target_Month__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Month Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Target__c/fields/Target_Month__c.field-meta.xml
<CustomField>
    <fullName>Target_Month__c</fullName>
    <label>Target Month</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Target__c/fields/Target_Value_In_Teus__c.field-meta.xml
<CustomField>
    <fullName>Target_Value_In_Teus__c</fullName>
    <label>Target Value (In Teus)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Target__c/fields/Year_Value__c.field-meta.xml
<CustomField>
    <fullName>Year_Value__c</fullName>
    <formula>Year(Target_Month__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BAFCOOrderItemTriggerHandler.cls
public class BAFCOOrderItemTriggerHandler {
    public static void addTargetValue(List<Order_Item__c> orderItemList){
        set<ID> ownerIDSet = new SET<ID>();
        set<ID> orderIDSet = new SET<ID>();
        Map<Id,Target__c> targetOwnerMap = new Map<Id,Target__c>();
        List<Target__c> targetListToUpdate = new List<Target__c>();
        List<Order__c> orderListToUpdate = new List<Order__c>();
        Date dt = System.today();
        Integer currentMonth = dt.Month();
        Integer currentYear = dt.Year();
        Map<ID,String> oppOwnerMap = new Map<ID,String>();
        for(Order_Item__c ord:orderItemList){   
            ownerIDSet.add(ord.Order__r.Opportunity_Order__r.Owner.ID);
            orderIDSet.add(ord.Order__c);
        } 
        for(Order__c ordForOwner : [Select id,Opportunity_Order__r.OwnerID FROM Order__c where ID IN : orderIDSet]){
            oppOwnerMap.put(ordForOwner.ID,ordForOwner.Opportunity_Order__r.OwnerID);
        }
        for(Target__c targetRec : [Select ID,Target_Value_In_Teus__c,Achieved_Value_In_Teus__c,Target_Month__c,OwnerId,Year_Value__c,Month_Value__c FROM Target__c Where OwnerId IN:oppOwnerMap.values() 
                                   AND Month_Value__c=:currentMonth AND Year_Value__c=:currentYear]){
                                       targetOwnerMap.put(targetRec.OwnerId,targetRec);  
                                   }
        if(targetOwnerMap!=NULL){
            for(Order_Item__c ordItem : orderItemList){
                Target__c targetRec = targetOwnerMap.get(oppOwnerMap.get(ordItem.Order__c));                
                //system.debug('targetRec.Achieved_Value_In_Teus__c '+targetRec.Achieved_Value_In_Teus__c+'ordItem.Teus__c '+ordItem.Teus__c);
                if(targetRec!=null && ordItem.Teus__c!=null && targetRec.Achieved_Value_In_Teus__c!=null){
                    targetRec.Achieved_Value_In_Teus__c  = targetRec.Achieved_Value_In_Teus__c + ordItem.Teus__c;
                    targetListToUpdate.add(targetRec);
                    Order__c ordRec = new Order__c(Id=ordItem.Order__c);
                    ordRec.Target__c = targetOwnerMap.get(oppOwnerMap.get(ordItem.Order__c)).ID;            
                    orderListToUpdate.add(ordRec);
                    
                }
            }
        }
        if(targetListToUpdate!=NULL){
            database.update(targetListToUpdate);
        }
        if(orderListToUpdate!=NULL){
            database.update(orderListToUpdate);
        }
    }
    
    public static void removeTargetValue(List<Order_Item__c> orderItemList){
        set<ID> ownerIDSet = new SET<ID>();
        set<ID> orderIDSet = new SET<ID>();
        Map<Id,Target__c> targetOwnerMap = new Map<Id,Target__c>();
        List<Target__c> targetListToUpdate = new List<Target__c>();
        List<Order__c> orderListToUpdate = new List<Order__c>();
        Date dt = System.today();
        Integer currentMonth = dt.Month();
        Integer currentYear = dt.Year();
        Map<ID,String> oppOwnerMap = new Map<ID,String>();
        for(Order_Item__c ord:orderItemList){   
            ownerIDSet.add(ord.Order__r.Opportunity_Order__r.Owner.ID);
            orderIDSet.add(ord.Order__c);
        } 
        for(Order__c ordForOwner : [Select id,Opportunity_Order__r.OwnerID FROM Order__c where ID IN : orderIDSet]){
            oppOwnerMap.put(ordForOwner.ID,ordForOwner.Opportunity_Order__r.OwnerID);
        }
        for(Target__c targetRec : [Select ID,Target_Value_In_Teus__c,Achieved_Value_In_Teus__c,Target_Month__c,OwnerId,Year_Value__c,Month_Value__c FROM Target__c Where OwnerId IN:oppOwnerMap.values() 
                                   AND Month_Value__c=:currentMonth AND Year_Value__c=:currentYear]){
                                       targetOwnerMap.put(targetRec.OwnerId,targetRec);  
                                   }
        if(targetOwnerMap!=NULL){
            for(Order_Item__c ordItem : orderItemList){
                Target__c targetRec = targetOwnerMap.get(oppOwnerMap.get(ordItem.Order__c));
                //system.debug('targetRec.Achieved_Value_In_Teus__c '+targetRec.Achieved_Value_In_Teus__c+'ordItem.Teus__c '+ordItem.Teus__c);
                if(targetRec!=NULL && ordItem.Teus__c!=NULL && targetRec.Achieved_Value_In_Teus__c!=NULL){
                    targetRec.Achieved_Value_In_Teus__c  =targetRec.Achieved_Value_In_Teus__c -  ordItem.Teus__c;
                    targetListToUpdate.add(targetRec);
                    Order__c ordRec = new Order__c(Id=ordItem.Order__c);
                    ordRec.Target__c = targetOwnerMap.get(oppOwnerMap.get(ordItem.Order__c)).ID;            
                    orderListToUpdate.add(ordRec);
                    
                }
            }
        }
        if(targetListToUpdate!=NULL){
            database.update(targetListToUpdate);
        }
        if(orderListToUpdate!=NULL){
            database.update(orderListToUpdate);
        }
    }
    public static void onAfterInsert(List<Order_Item__c> orderItemList){
        createRegularRoute(orderItemList);
    }
    public static void createRegularRoute(List<Order_Item__c> orderItemList){
        Set<Id> orderIds = new Set<Id>();
        Set<Id> polIds = new Set<Id>();
        Set<Id> podIds = new Set<Id>();
        Set<Id> accIds = new Set<Id>();
        Map<Id,Id> orderIdToAccId = new Map<Id,Id>();
        Map<Id,List<Regular_Routing__c>> accIdToRegularRoute = new Map<Id,List<Regular_Routing__c>>();
        List<Regular_Routing__c> regList = new List<Regular_Routing__c>();
        for(Order_Item__c item : orderItemList){
            orderIds.add(item.Order__c);
        }
        for(Order__c orderObj : [Select id, Account_Order__c from order__c where id in : orderIds]){
            if(orderObj.Account_Order__c != null ) orderIdToAccId.put(orderObj.id,orderObj.Account_Order__c);
        }
        for(Order_Item__c item : orderItemList){
            if(item.Port_of_Loading_Order__c != null) polIds.add(item.Port_of_Loading_Order__c);
            if(item.Port_of_Discharge_Order__c != null) podIds.add(item.Port_of_Discharge_Order__c); 
            if(item.Order__c != null && orderIdToAccId.containsKey(item.Order__c)) accIds.add(orderIdToAccId.get(item.Order__c));
        }
        for(Regular_Routing__c regObj : [Select id,Account__c,Port_of_Loading__c,Port_of_Destination__c from Regular_Routing__c where Account__c in : accIds OR Port_of_Loading__c in : polIds OR Port_of_Destination__c in : podIds]){
            if(!accIdToRegularRoute.containsKey(regObj.Account__c)){
                accIdToRegularRoute.put(regObj.Account__c, new List<Regular_Routing__c>());
            }
            accIdToRegularRoute.get(regObj.Account__c).add(regObj);
        }
        for(Order_Item__c item : orderItemList){
            List<Regular_Routing__c> reguLarList = new List<Regular_Routing__c>();
            if(item.Order__c != null && orderIdToAccId.containsKey(item.Order__c)){
                if(accIdToRegularRoute.containskey(orderIdToAccId.get(item.Order__c)))
                    reguLarList = accIdToRegularRoute.get(orderIdToAccId.get(item.Order__c));
            }
            if(reguLarList.size() > 0){
                Boolean similarFound = false;
                for(Regular_Routing__c regObj : reguLarList){
                    if(regObj.Account__c != null){
                        if(regObj.Port_of_Loading__c != null){
                            if(regObj.Port_of_Destination__c != null){
                                if(orderIdToAccId.get(item.Order__c) == regObj.Account__c && regObj.Port_of_Destination__c == item.Port_of_Discharge_Order__c && regObj.Port_of_Loading__c == item.Port_of_Loading_Order__c){
                                    similarFound = true;
                                }
                            }
                            else if(orderIdToAccId.get(item.Order__c) == regObj.Account__c && regObj.Port_of_Loading__c == item.Port_of_Loading_Order__c && item.Port_of_Discharge_Order__c == null){
                                similarFound = true;
                            }
                        }
                        else if(regObj.Port_of_Destination__c != null){
                            if(orderIdToAccId.get(item.Order__c) == regObj.Account__c && regObj.Port_of_Destination__c == item.Port_of_Discharge_Order__c && item.Port_of_Loading_Order__c == null){
                                similarFound = true;
                            }
                        }
                    }
                    else if(regObj.Port_of_Loading__c != null){
                        if(regObj.Port_of_Destination__c != null){
                            if(regObj.Port_of_Loading__c == item.Port_of_Loading_Order__c && regObj.Port_of_Destination__c == item.Port_of_Discharge_Order__c){
                                similarFound = true;
                            }
                        }
                        else if(regObj.Port_of_Loading__c == item.Port_of_Loading_Order__c && item.Port_of_Discharge_Order__c == null){
                            similarFound = true;
                        }
                    }
                    else if(regObj.Port_of_Destination__c != null &&  regObj.Port_of_Destination__c == item.Port_of_Discharge_Order__c && item.Port_of_Loading_Order__c == null){
                        similarFound = true;
                    }
                }
                if(similarFound == false) regList.add(createRegularRouteObj(item,orderIdToAccId));
            }
            else{
                regList.add(createRegularRouteObj(item,orderIdToAccId));
            }
        }
        if(regList.size() > 0) insert regList;
    }
    public static Regular_Routing__c createRegularRouteObj(Order_Item__c item,Map<Id,Id> orderIdToAccId){
        Regular_Routing__c newObj = new Regular_Routing__c();
        newObj.Account__c = orderIdToAccId.containsKey(item.Order__c) ? orderIdToAccId.get(item.Order__c) : null;
        newObj.Port_of_Destination__c = item.Port_of_Discharge_Order__c;
        newObj.Port_of_Loading__c = item.Port_of_Loading_Order__c;
        newObj.Shipping_Line__c = item.Shipping_Line__c;
        newObj.Pickup_Place__c = item.Pickup_Place__c;
        newObj.Place_of_Discharge__c = item.Place_of_Discharge__c;
        return newObj;
    }
}