force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>ORD-{MM}/{YY}-{000}</displayFormat>
        <label>Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>Order Item-{0000}</displayFormat>
        <label>Order Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Vessel_ETD__c.field-meta.xml
<CustomField>
    <fullName>Vessel_ETD__c</fullName>
    <label>Vessel ETD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/BAFCOUpdatETDOnOrderAPI.cls
@RestResource(urlMapping='/OrderUpdate/UpdateETDValue/*')
global class BAFCOUpdatETDOnOrderAPI{    
    @HttpPost
    global static ETDResponseBodyWrapper doPost(){
        ETDResponseBodyWrapper responseWrapper = new ETDResponseBodyWrapper();
        String UpdatedOrderNumber;
        try{
            RestRequest req = RestContext.request;
            String requestBody = req.requestBody.toString();
            List<Order_Item__c> OrderItemList = new List<Order_Item__c>();
            ETDRequestBodyWrapper reqWrapper = (ETDRequestBodyWrapper) JSON.deserialize(requestBody, ETDRequestBodyWrapper.class);
            Order__c Order = [Select Id FROM Order__c WHERE Name = :reqWrapper.OrderNumber Limit 1];
            if(Order != null){
                OrderItemList = [Select Id , Vessel_ETD__c FROM Order_Item__c WHERE Order__c =: Order.Id];
                Set<Id> accountIds = new Set<Id>();
                for(Order_Item__c OrderItem : OrderItemList){
                    OrderItem.Vessel_ETD__c=reqWrapper.VesselETD;
                }
                database.update(OrderItemList);                        
            }
            
            if(!OrderItemList.IsEmpty()){
                responseWrapper.StatusCode = '200';
                responseWrapper.Message = 'Status Code :200 -- Order Details Updated Successfully for :'+reqWrapper.OrderNumber;
            }else{
                responseWrapper.message = 'No Order Information found with respect to provided Number :'+reqWrapper.OrderNumber;
            }
            
            
        }catch(Exception e){
            responseWrapper.message = 'Exception :'+e.getMessage()+' '+e.getLineNumber();
        }
        return responseWrapper;
    }
    
    global class ETDResponseBodyWrapper{
        public String Message {get;set;}
        public String StatusCode {get;set;}
    }
    
    global class ETDRequestBodyWrapper{
        public String OrderNumber {get;set;}
        public Date VesselETD {get;set;}        
    }
}