force-app/main/default/objects/Equipment_Type__c/Equipment_Type__c.object-meta.xml
<CustomObject>
    <label>Equipment Type</label>
    <nameField>
        <label>Equipment Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipment Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Port__c/Port__c.object-meta.xml
<CustomObject>
    <label>Port</label>
    <nameField>
        <label>Port Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotation__c/Quotation__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>JED-{MM}/{YY}-{000}</displayFormat>
        <label>Quotation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotation__c/fields/Exclusions__c.field-meta.xml
<CustomField>
    <fullName>Exclusions__c</fullName>
    <label>Exclusions</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Inclusions__c.field-meta.xml
<CustomField>
    <fullName>Inclusions__c</fullName>
    <label>Inclusions</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Terms_and_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Terms_and_Conditions__c</fullName>
    <label>Terms and Conditions</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <label>Total</label>
    <summarizedField>Quotation_Item__c.Total__c</summarizedField>
    <summaryForeignKey>Quotation_Item__c.Quotation__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quotation__c/recordTypes/Export.recordType-meta.xml
<RecordType>
    <fullName>Export</fullName>
    <active>true</active>
    <label>Export</label>
</RecordType>

force-app/main/default/objects/Quotation__c/recordTypes/Import.recordType-meta.xml
<RecordType>
    <fullName>Import</fullName>
    <active>true</active>
    <label>Import</label>
</RecordType>

force-app/main/default/objects/Quotation_Item__c/Quotation_Item__c.object-meta.xml
<CustomObject>
    <label>Quotation Item</label>
    <nameField>
        <label>Quotation Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotation Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotation_Item__c/fields/Equipment_Type__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment Type</label>
    <referenceTo>Equipment_Type__c</referenceTo>
    <relationshipLabel>Quotation Items</relationshipLabel>
    <relationshipName>Quotation_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation_Item__c/fields/Port_of_Discharge__c.field-meta.xml
<CustomField>
    <fullName>Port_of_Discharge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Port of Discharge</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipLabel>Quotation Items (Port of Discharge)</relationshipLabel>
    <relationshipName>Quotation_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation_Item__c/fields/Port_of_Loading__c.field-meta.xml
<CustomField>
    <fullName>Port_of_Loading__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Port of Loading</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipLabel>Quotation Items</relationshipLabel>
    <relationshipName>Quotation_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation_Item__c/fields/Quotation__c.field-meta.xml
<CustomField>
    <fullName>Quotation__c</fullName>
    <label>Quotation</label>
    <referenceTo>Quotation__c</referenceTo>
    <relationshipLabel>Quotation Items</relationshipLabel>
    <relationshipName>Quotation_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quotation_Item__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <label>Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/BAFCOQuoteCopyContentController.cls
public without sharing class BAFCOQuoteCopyContentController {
    @AuraEnabled 
    public static List<QuoteLineList>  getQuoteDataOnLoad(String quoteId){
        List<QuoteLineList> quoteItemList = new List<QuoteLineList>();
        List<Quotation_Item__c> quoteList = [Select id,Quotation__r.Exclusions__c,Quotation__r.Inclusions__c,Quotation__r.Terms_and_Conditions__c,Total__c,Quotation__r.Recordtype.Name,Port_of_Loading__r.Name,Port_of_Discharge__r.Name,Equipment_Type__r.Name from Quotation_Item__c where quotation__c =: quoteId];
        if(quoteList.size() > 0){
            for(Quotation_Item__c item : quoteList){
                QuoteLineList dto = new QuoteLineList();
                dto.loadingPort = item.Port_of_Loading__c != null ? item.Port_of_Loading__r.Name : '';
                dto.dischargePort = item.Port_of_Discharge__c != null ? item.Port_of_Discharge__r.Name : '';
                dto.equipmentType = item.Equipment_Type__c != null ? item.Equipment_Type__r.Name : '';
                dto.total = item.Total__c;
                dto.recordtypeName = item.Quotation__r.Recordtype.Name;
                if(item.Quotation__r.Recordtype.Name == 'Export'){
                    List<String> inclusionList = item.Quotation__r.Inclusions__c != null ? item.Quotation__r.Inclusions__c.split(';;') : null; 
                    if(inclusionList != null && inclusionList.size() > 0){
                        dto.header = inclusionList[0] != null ? inclusionList[0] : null;
                        if(inclusionList.size() >1){
                            dto.headerList = inclusionList[1].split(';');
                        }
                    }
                    List<String> exclusionList =item.Quotation__r.Exclusions__c != null ? item.Quotation__r.Exclusions__c.split(';;') : null; 
                    if(exclusionList != null && exclusionList.size() > 0){
                        dto.exportHeader = exclusionList[0] != null ? exclusionList[0] : null;
                        if(exclusionList.size() >1){
                            dto.exportHeaderList = exclusionList[1].split(';');
                        }
                    }
                }
                else if(item.Quotation__r.Recordtype.Name == 'Import'){
                    List<String> termsList =item.Quotation__r.Terms_and_Conditions__c != null ? item.Quotation__r.Terms_and_Conditions__c.split(';;') : null; 
                    if(termsList != null && termsList.size() > 0){
                        dto.header = termsList[0] != null ? termsList[0] : null;
                        if(termsList.size() >1){
                            dto.headerList = termsList[1].split(';');
                        }
                    }
                }
                quoteItemList.add(dto);
            }
        }
        return quoteItemList;
    }
    public class QuoteLineList{
        @AuraEnabled public String loadingPort{get;set;}
        @AuraEnabled public String dischargePort{get;set;}
        @AuraEnabled public String equipmentType{get;set;}
        @AuraEnabled public Decimal total{get;set;}
        @AuraEnabled public String recordtypeName{get;set;}
        @AuraEnabled public String header{get;set;}
        @AuraEnabled public List<String> headerList{get;set;}
        @AuraEnabled public String exportHeader{get;set;}
        @AuraEnabled public List<String> exportHeaderList{get;set;}
    }
}