force-app/main/default/objects/Destination_Charges__c/Destination_Charges__c.object-meta.xml
<CustomObject>
    <label>Destination Charges</label>
    <nameField>
        <displayFormat>Dest-Charge-{0000}</displayFormat>
        <label>Destination Charge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Destination Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Destination_Charges__c/fields/Bayan_Charges__c.field-meta.xml
<CustomField>
    <fullName>Bayan_Charges__c</fullName>
    <label>Bayan Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Destination_Charges__c/fields/RMS__c.field-meta.xml
<CustomField>
    <fullName>RMS__c</fullName>
    <label>RMS</label>
    <referenceTo>RMS__c</referenceTo>
    <relationshipName>Clearance_and_Delivery</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/INCO_Charge__c/INCO_Charge__c.object-meta.xml
<CustomObject>
    <label>Origin Charge</label>
    <nameField>
        <displayFormat>Origin-Charge-{0000}</displayFormat>
        <label>Origin Charge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Origin Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/INCO_Charge__c/fields/Bayan__c.field-meta.xml
<CustomField>
    <fullName>Bayan__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Bayan</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/INCO_Charge__c/fields/RMS__c.field-meta.xml
<CustomField>
    <fullName>RMS__c</fullName>
    <label>RMS</label>
    <referenceTo>RMS__c</referenceTo>
    <relationshipName>INCO_Charges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Port__c/Port__c.object-meta.xml
<CustomObject>
    <label>Port</label>
    <nameField>
        <label>Port Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Port__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RMS__c/RMS__c.object-meta.xml
<CustomObject>
    <label>RMS</label>
    <nameField>
        <label>RMS Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS__c/fields/Port_Of_Discharge__c.field-meta.xml
<CustomField>
    <fullName>Port_Of_Discharge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Port Of Discharge</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipLabel>RMS (Port Of Discharge)</relationshipLabel>
    <relationshipName>RMS1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RMS__c/fields/Port_Of_Loading__c.field-meta.xml
<CustomField>
    <fullName>Port_Of_Loading__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Port Of Loading</label>
    <referenceTo>Port__c</referenceTo>
    <relationshipLabel>RMS</relationshipLabel>
    <relationshipName>RMS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Line_Charge__c/Shipping_Line_Charge__c.object-meta.xml
<CustomObject>
    <label>Shipping Line Charge</label>
    <nameField>
        <displayFormat>SL-Charge-{0000}</displayFormat>
        <label>SL Charge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Line Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Line_Charge__c/fields/BAF__c.field-meta.xml
<CustomField>
    <fullName>BAF__c</fullName>
    <inlineHelpText>Bunker Recovery Adjustment Charges</inlineHelpText>
    <label>BAF</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Shipping_Line_Charge__c/fields/RMS__c.field-meta.xml
<CustomField>
    <fullName>RMS__c</fullName>
    <label>RMS</label>
    <referenceTo>RMS__c</referenceTo>
    <relationshipLabel>Shipping Line Charges</relationshipLabel>
    <relationshipName>Shipping_Line_Charges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BAFCOshippingLineChargesControllerTest.cls
@isTest
public class BAFCOshippingLineChargesControllerTest {
	 @TestSetup
    static void setup() {
        Port__c port = new Port__c();
        port.City__c = 'Test';
        Insert port;
        
        RMS__c rmsObj = new RMS__c();
        rmsObj.Name ='Test';
        rmsObj.Port_Of_Discharge__c = port.Id;
        rmsObj.Port_Of_Loading__c = port.Id;
        insert rmsObj;
        
        Shipping_Line_Charge__c shipLine = new Shipping_Line_Charge__c();
        shipLine.BAF__c =12 ;
        shipLine.RMS__c = rmsObj.id;
        insert shipLine;
        Destination_Charges__c destiobj = new Destination_Charges__c();
        destiObj.Bayan_Charges__c = 1;
        destiObj.RMS__c = rmsObj.id;
        insert destiObj;
        INCO_Charge__c inco = new INCO_Charge__c();
        inco.Bayan__c = 12;
        inco.RMS__c  = rmsObj.id;
        insert inco;
    }
    testMethod static void getShippingChargesTest(){
        String rmsRecordId = [Select id from RMS__c limit 1].Id;
        test.startTest();
        try{
            BAFCOshippingLineChargesController.getRMSDetail(rmsRecordId);
            BAFCOshippingLineChargesController.getRMSDetail(null);
        }
        catch(Exception e){
            system.debug('getShippingChargesTest '+e);
        }
        test.stopTest();
    }
    testMethod static void getIncoChargesTest(){
        String rmsRecordId = [Select id from RMS__c limit 1].Id;
        test.startTest();
        try{
            BAFCOshippingLineChargesController.getIncoCharges(rmsRecordId);
        }
        catch(Exception e){
            system.debug('getIncoCharges '+e);
        }
        test.stopTest();
    }
    
}